package ir.parsikhesab.pakhsh;


import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.B4AClass;
import anywheresoftware.b4a.BALayout;
import anywheresoftware.b4a.debug.*;

public class cls_printmali extends B4AClass.ImplB4AClass implements BA.SubDelegator{
    private static java.util.HashMap<String, java.lang.reflect.Method> htSubs;
    private void innerInitialize(BA _ba) throws Exception {
        if (ba == null) {
            ba = new anywheresoftware.b4a.ShellBA(_ba, this, htSubs, "ir.parsikhesab.pakhsh.cls_printmali");
            if (htSubs == null) {
                ba.loadHtSubs(this.getClass());
                htSubs = ba.htSubs;
            }
            
        }
        if (BA.isShellModeRuntimeCheck(ba)) 
			   this.getClass().getMethod("_class_globals", ir.parsikhesab.pakhsh.cls_printmali.class).invoke(this, new Object[] {null});
        else
            ba.raiseEvent2(null, true, "class_globals", false);
    }

 
    public void  innerInitializeHelper(anywheresoftware.b4a.BA _ba) throws Exception{
        innerInitialize(_ba);
    }
    public Object callSub(String sub, Object sender, Object[] args) throws Exception {
        return BA.SubDelegator.SubNotFound;
    }
public anywheresoftware.b4a.keywords.Common __c = null;
public anywheresoftware.b4a.objects.PanelWrapper _p = null;
public anywheresoftware.b4a.objects.PanelWrapper _pnl_bk = null;
public anywheresoftware.b4a.objects.LabelWrapper _lbltarikh = null;
public anywheresoftware.b4a.objects.LabelWrapper _lblnamemoshtari = null;
public anywheresoftware.b4a.objects.LabelWrapper _lbladress = null;
public anywheresoftware.b4a.objects.LabelWrapper _lbltel = null;
public anywheresoftware.b4a.objects.LabelWrapper _lbltitle = null;
public anywheresoftware.b4a.objects.PanelWrapper _parent = null;
public anywheresoftware.b4a.objects.LabelWrapper _label1 = null;
public igolub.fused.b4a.location.android.location.LocationFWrapper.LocationFStatic _locationf = null;
public igolub.fused.b4a.location.LocationResultWrapper.LocationResultConstants _locationresult = null;
public igolub.fused.b4a.location.LocationRequestWrapper.LocationRequestConstants _locationrequest = null;
public igolub.fused.b4a.location.staticmodules.PriorityWrapper _priority = null;
public igolub.fused.b4a.location.staticmodules.GranularityWrapper _granularity = null;
public igolub.permissionmanager.b4a.PermissionsManagerFileProvider _fileprovider = null;
public igolub.permissionmanager.b4a.PermissionsManagerConstants _permissionsmanager = null;
public b4a.example.dateutils _dateutils = null;
public ir.parsikhesab.pakhsh.main _main = null;
public ir.parsikhesab.pakhsh.act_main _act_main = null;
public ir.parsikhesab.pakhsh.service_server _service_server = null;
public ir.parsikhesab.pakhsh.mcode _mcode = null;
public ir.parsikhesab.pakhsh.mycode _mycode = null;
public ir.parsikhesab.pakhsh.mdatabase _mdatabase = null;
public ir.parsikhesab.pakhsh.gpswiget _gpswiget = null;
public ir.parsikhesab.pakhsh.fusedlocationservice _fusedlocationservice = null;
public ir.parsikhesab.pakhsh.service_helper _service_helper = null;
public ir.parsikhesab.pakhsh.act_selectmantage _act_selectmantage = null;
public ir.parsikhesab.pakhsh.act_reprizfactorvisitor _act_reprizfactorvisitor = null;
public ir.parsikhesab.pakhsh.act_choose_report _act_choose_report = null;
public ir.parsikhesab.pakhsh.act_emza _act_emza = null;
public ir.parsikhesab.pakhsh.act_havaletozie _act_havaletozie = null;
public ir.parsikhesab.pakhsh.act_imageslideshow _act_imageslideshow = null;
public ir.parsikhesab.pakhsh.act_kala_listi _act_kala_listi = null;
public ir.parsikhesab.pakhsh.act_kaladefault _act_kaladefault = null;
public ir.parsikhesab.pakhsh.act_kalapaging _act_kalapaging = null;
public ir.parsikhesab.pakhsh.act_kalapaging2 _act_kalapaging2 = null;
public ir.parsikhesab.pakhsh.act_locationmoshtarian _act_locationmoshtarian = null;
public ir.parsikhesab.pakhsh.act_locationvisitor _act_locationvisitor = null;
public ir.parsikhesab.pakhsh.act_mali _act_mali = null;
public ir.parsikhesab.pakhsh.act_moshtarian _act_moshtarian = null;
public ir.parsikhesab.pakhsh.act_newashkhas _act_newashkhas = null;
public ir.parsikhesab.pakhsh.act_notif _act_notif = null;
public ir.parsikhesab.pakhsh.act_printmali _act_printmali = null;
public ir.parsikhesab.pakhsh.act_printpic _act_printpic = null;
public ir.parsikhesab.pakhsh.act_printpic2 _act_printpic2 = null;
public ir.parsikhesab.pakhsh.act_profile _act_profile = null;
public ir.parsikhesab.pakhsh.act_repfactors _act_repfactors = null;
public ir.parsikhesab.pakhsh.act_repfactorvisitor _act_repfactorvisitor = null;
public ir.parsikhesab.pakhsh.act_reportrizebargasht _act_reportrizebargasht = null;
public ir.parsikhesab.pakhsh.act_reportsoorathesab _act_reportsoorathesab = null;
public ir.parsikhesab.pakhsh.act_reportvisitor _act_reportvisitor = null;
public ir.parsikhesab.pakhsh.act_reportvisitor2 _act_reportvisitor2 = null;
public ir.parsikhesab.pakhsh.act_restore _act_restore = null;
public ir.parsikhesab.pakhsh.act_rizefactorhavale _act_rizefactorhavale = null;
public ir.parsikhesab.pakhsh.act_rizfaktor _act_rizfaktor = null;
public ir.parsikhesab.pakhsh.act_rizhavale _act_rizhavale = null;
public ir.parsikhesab.pakhsh.act_sabad _act_sabad = null;
public ir.parsikhesab.pakhsh.act_sabtmarjooii _act_sabtmarjooii = null;
public ir.parsikhesab.pakhsh.act_sabtrizcheck _act_sabtrizcheck = null;
public ir.parsikhesab.pakhsh.act_saveinfocompany _act_saveinfocompany = null;
public ir.parsikhesab.pakhsh.act_savelocation _act_savelocation = null;
public ir.parsikhesab.pakhsh.act_search _act_search = null;
public ir.parsikhesab.pakhsh.act_selfaktor _act_selfaktor = null;
public ir.parsikhesab.pakhsh.act_senddata _act_senddata = null;
public ir.parsikhesab.pakhsh.act_setting _act_setting = null;
public ir.parsikhesab.pakhsh.act_settingpos _act_settingpos = null;
public ir.parsikhesab.pakhsh.act_showlocation _act_showlocation = null;
public ir.parsikhesab.pakhsh.act_support _act_support = null;
public ir.parsikhesab.pakhsh.act_ticket _act_ticket = null;
public ir.parsikhesab.pakhsh.act_video _act_video = null;
public ir.parsikhesab.pakhsh.clskala _clskala = null;
public ir.parsikhesab.pakhsh.dbutils _dbutils = null;
public ir.parsikhesab.pakhsh.firebasemessaging _firebasemessaging = null;
public ir.parsikhesab.pakhsh.geoservice _geoservice = null;
public ir.parsikhesab.pakhsh.imagedownloader _imagedownloader = null;
public ir.parsikhesab.pakhsh.myreceiver _myreceiver = null;
public ir.parsikhesab.pakhsh.service_gps _service_gps = null;
public ir.parsikhesab.pakhsh.service_notification _service_notification = null;
public ir.parsikhesab.pakhsh.signaturecapture _signaturecapture = null;
public ir.parsikhesab.pakhsh.starter _starter = null;
public ir.parsikhesab.pakhsh.tracker _tracker = null;
public ir.parsikhesab.pakhsh.wiget_service _wiget_service = null;
public ir.parsikhesab.pakhsh.xmlviewex _xmlviewex = null;
public ir.parsikhesab.pakhsh.newinst2 _newinst2 = null;
public ir.parsikhesab.pakhsh.base64encodedecodeimage _base64encodedecodeimage = null;
public ir.parsikhesab.pakhsh.httputils2service _httputils2service = null;
public ir.parsikhesab.pakhsh.xuiviewsutils _xuiviewsutils = null;
public String  _initialize(ir.parsikhesab.pakhsh.cls_printmali __ref,anywheresoftware.b4a.BA _ba,String _tarikh,String _name,String _address,String _tel,String _pardakhti,anywheresoftware.b4a.sql.SQL.CursorWrapper _cu) throws Exception{
__ref = this;
innerInitialize(_ba);
RDebugUtils.currentModule="cls_printmali";
if (Debug.shouldDelegate(ba, "initialize", false))
	 {return ((String) Debug.delegate(ba, "initialize", new Object[] {_ba,_tarikh,_name,_address,_tel,_pardakhti,_cu}));}
anywheresoftware.b4a.objects.LabelWrapper _lbldatesabt = null;
anywheresoftware.b4a.objects.LabelWrapper _lblshomaresabt = null;
anywheresoftware.b4a.objects.LabelWrapper _lbltypesabt = null;
anywheresoftware.b4a.objects.LabelWrapper _lblnoesabt = null;
anywheresoftware.b4a.objects.LabelWrapper _lblnamebank = null;
anywheresoftware.b4a.objects.LabelWrapper _lblmablagh = null;
anywheresoftware.b4a.objects.LabelWrapper _lblshomarecheck = null;
anywheresoftware.b4a.objects.LabelWrapper _lbldatecheck = null;
ir.parsikhesab.pakhsh.mcode._adapterlistsabt _item = null;
RDebugUtils.currentLine=96993280;
 //BA.debugLineNum = 96993280;BA.debugLine="Public Sub Initialize(tarikh As String,name As Str";
RDebugUtils.currentLine=96993281;
 //BA.debugLineNum = 96993281;BA.debugLine="p.Initialize(\"\")";
__ref._p /*anywheresoftware.b4a.objects.PanelWrapper*/ .Initialize(ba,"");
RDebugUtils.currentLine=96993282;
 //BA.debugLineNum = 96993282;BA.debugLine="p.SetLayout(0,0,100%x,100%y)";
__ref._p /*anywheresoftware.b4a.objects.PanelWrapper*/ .SetLayout((int) (0),(int) (0),__c.PerXToCurrent((float) (100),ba),__c.PerYToCurrent((float) (100),ba));
RDebugUtils.currentLine=96993283;
 //BA.debugLineNum = 96993283;BA.debugLine="p.LoadLayout(\"L_PrintMali\")";
__ref._p /*anywheresoftware.b4a.objects.PanelWrapper*/ .LoadLayout("L_PrintMali",ba);
RDebugUtils.currentLine=96993284;
 //BA.debugLineNum = 96993284;BA.debugLine="lblAdress.Text=\"آدرس:\"&address";
__ref._lbladress /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("آدرس:"+_address));
RDebugUtils.currentLine=96993285;
 //BA.debugLineNum = 96993285;BA.debugLine="LblNameMoshtari.Text=\"نام مشتری:\"&name";
__ref._lblnamemoshtari /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("نام مشتری:"+_name));
RDebugUtils.currentLine=96993286;
 //BA.debugLineNum = 96993286;BA.debugLine="lblTarikh.Text=tarikh";
__ref._lbltarikh /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence(_tarikh));
RDebugUtils.currentLine=96993287;
 //BA.debugLineNum = 96993287;BA.debugLine="lblTel.Text=\"تلفن:\"&tel";
__ref._lbltel /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("تلفن:"+_tel));
RDebugUtils.currentLine=96993289;
 //BA.debugLineNum = 96993289;BA.debugLine="Label1.Text = MCode.AppName";
__ref._label1 /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence(_mcode._appname /*String*/ ));
RDebugUtils.currentLine=96993292;
 //BA.debugLineNum = 96993292;BA.debugLine="cu.Position=0";
_cu.setPosition((int) (0));
RDebugUtils.currentLine=96993294;
 //BA.debugLineNum = 96993294;BA.debugLine="Dim LblDateSabt As Label";
_lbldatesabt = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96993295;
 //BA.debugLineNum = 96993295;BA.debugLine="LblDateSabt.Initialize(\"LblDateSabt\")";
_lbldatesabt.Initialize(ba,"LblDateSabt");
RDebugUtils.currentLine=96993296;
 //BA.debugLineNum = 96993296;BA.debugLine="LblDateSabt.TextColor=Colors.Black";
_lbldatesabt.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=96993297;
 //BA.debugLineNum = 96993297;BA.debugLine="LblDateSabt.TextSize=16";
_lbldatesabt.setTextSize((float) (16));
RDebugUtils.currentLine=96993298;
 //BA.debugLineNum = 96993298;BA.debugLine="LblDateSabt.Gravity=Gravity.Right";
_lbldatesabt.setGravity(__c.Gravity.RIGHT);
RDebugUtils.currentLine=96993299;
 //BA.debugLineNum = 96993299;BA.debugLine="LblDateSabt.SingleLine=False";
_lbldatesabt.setSingleLine(__c.False);
RDebugUtils.currentLine=96993300;
 //BA.debugLineNum = 96993300;BA.debugLine="LblDateSabt.Typeface=MCode.Font2";
_lbldatesabt.setTypeface((android.graphics.Typeface)(_mcode._font2 /*anywheresoftware.b4a.keywords.constants.TypefaceWrapper*/ .getObject()));
RDebugUtils.currentLine=96993301;
 //BA.debugLineNum = 96993301;BA.debugLine="LblDateSabt.Color=Colors.Transparent";
_lbldatesabt.setColor(__c.Colors.Transparent);
RDebugUtils.currentLine=96993302;
 //BA.debugLineNum = 96993302;BA.debugLine="Parent.AddView(LblDateSabt,1%x,1%y,49%x,5%y)";
__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_lbldatesabt.getObject()),__c.PerXToCurrent((float) (1),ba),__c.PerYToCurrent((float) (1),ba),__c.PerXToCurrent((float) (49),ba),__c.PerYToCurrent((float) (5),ba));
RDebugUtils.currentLine=96993304;
 //BA.debugLineNum = 96993304;BA.debugLine="Dim LblShomareSabt As Label";
_lblshomaresabt = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96993305;
 //BA.debugLineNum = 96993305;BA.debugLine="LblShomareSabt.Initialize(\"LblShomareSabt\")";
_lblshomaresabt.Initialize(ba,"LblShomareSabt");
RDebugUtils.currentLine=96993306;
 //BA.debugLineNum = 96993306;BA.debugLine="LblShomareSabt.TextColor=Colors.Black";
_lblshomaresabt.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=96993307;
 //BA.debugLineNum = 96993307;BA.debugLine="LblShomareSabt.TextSize=16";
_lblshomaresabt.setTextSize((float) (16));
RDebugUtils.currentLine=96993308;
 //BA.debugLineNum = 96993308;BA.debugLine="LblShomareSabt.Gravity=Gravity.Right";
_lblshomaresabt.setGravity(__c.Gravity.RIGHT);
RDebugUtils.currentLine=96993309;
 //BA.debugLineNum = 96993309;BA.debugLine="LblShomareSabt.SingleLine=False";
_lblshomaresabt.setSingleLine(__c.False);
RDebugUtils.currentLine=96993310;
 //BA.debugLineNum = 96993310;BA.debugLine="LblShomareSabt.Typeface=MCode.Font2";
_lblshomaresabt.setTypeface((android.graphics.Typeface)(_mcode._font2 /*anywheresoftware.b4a.keywords.constants.TypefaceWrapper*/ .getObject()));
RDebugUtils.currentLine=96993311;
 //BA.debugLineNum = 96993311;BA.debugLine="LblShomareSabt.Color=Colors.Transparent";
_lblshomaresabt.setColor(__c.Colors.Transparent);
RDebugUtils.currentLine=96993312;
 //BA.debugLineNum = 96993312;BA.debugLine="Parent.AddView(LblShomareSabt,50%x,1%y,46%x,5%y)";
__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_lblshomaresabt.getObject()),__c.PerXToCurrent((float) (50),ba),__c.PerYToCurrent((float) (1),ba),__c.PerXToCurrent((float) (46),ba),__c.PerYToCurrent((float) (5),ba));
RDebugUtils.currentLine=96993314;
 //BA.debugLineNum = 96993314;BA.debugLine="Dim LblTypeSabt As Label";
_lbltypesabt = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96993315;
 //BA.debugLineNum = 96993315;BA.debugLine="LblTypeSabt.Initialize(\"LblTypeSabt\")";
_lbltypesabt.Initialize(ba,"LblTypeSabt");
RDebugUtils.currentLine=96993316;
 //BA.debugLineNum = 96993316;BA.debugLine="LblTypeSabt.TextColor=Colors.Black";
_lbltypesabt.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=96993317;
 //BA.debugLineNum = 96993317;BA.debugLine="LblTypeSabt.TextSize=16";
_lbltypesabt.setTextSize((float) (16));
RDebugUtils.currentLine=96993318;
 //BA.debugLineNum = 96993318;BA.debugLine="LblTypeSabt.Gravity=Gravity.Right";
_lbltypesabt.setGravity(__c.Gravity.RIGHT);
RDebugUtils.currentLine=96993319;
 //BA.debugLineNum = 96993319;BA.debugLine="LblTypeSabt.SingleLine=False";
_lbltypesabt.setSingleLine(__c.False);
RDebugUtils.currentLine=96993320;
 //BA.debugLineNum = 96993320;BA.debugLine="LblTypeSabt.Typeface=MCode.Font2";
_lbltypesabt.setTypeface((android.graphics.Typeface)(_mcode._font2 /*anywheresoftware.b4a.keywords.constants.TypefaceWrapper*/ .getObject()));
RDebugUtils.currentLine=96993321;
 //BA.debugLineNum = 96993321;BA.debugLine="LblTypeSabt.Color=Colors.Transparent";
_lbltypesabt.setColor(__c.Colors.Transparent);
RDebugUtils.currentLine=96993322;
 //BA.debugLineNum = 96993322;BA.debugLine="Parent.AddView(LblTypeSabt,1%x,6%y,49%x,5%y)";
__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_lbltypesabt.getObject()),__c.PerXToCurrent((float) (1),ba),__c.PerYToCurrent((float) (6),ba),__c.PerXToCurrent((float) (49),ba),__c.PerYToCurrent((float) (5),ba));
RDebugUtils.currentLine=96993324;
 //BA.debugLineNum = 96993324;BA.debugLine="Dim LblNoeSabt As Label";
_lblnoesabt = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96993325;
 //BA.debugLineNum = 96993325;BA.debugLine="LblNoeSabt.Initialize(\"LblNoeSabt\")";
_lblnoesabt.Initialize(ba,"LblNoeSabt");
RDebugUtils.currentLine=96993326;
 //BA.debugLineNum = 96993326;BA.debugLine="LblNoeSabt.TextColor=Colors.Black";
_lblnoesabt.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=96993327;
 //BA.debugLineNum = 96993327;BA.debugLine="LblNoeSabt.TextSize=16";
_lblnoesabt.setTextSize((float) (16));
RDebugUtils.currentLine=96993328;
 //BA.debugLineNum = 96993328;BA.debugLine="LblNoeSabt.Gravity=Gravity.Right";
_lblnoesabt.setGravity(__c.Gravity.RIGHT);
RDebugUtils.currentLine=96993329;
 //BA.debugLineNum = 96993329;BA.debugLine="LblNoeSabt.SingleLine=False";
_lblnoesabt.setSingleLine(__c.False);
RDebugUtils.currentLine=96993330;
 //BA.debugLineNum = 96993330;BA.debugLine="LblNoeSabt.Typeface=MCode.Font2";
_lblnoesabt.setTypeface((android.graphics.Typeface)(_mcode._font2 /*anywheresoftware.b4a.keywords.constants.TypefaceWrapper*/ .getObject()));
RDebugUtils.currentLine=96993331;
 //BA.debugLineNum = 96993331;BA.debugLine="LblNoeSabt.Color=Colors.Transparent";
_lblnoesabt.setColor(__c.Colors.Transparent);
RDebugUtils.currentLine=96993332;
 //BA.debugLineNum = 96993332;BA.debugLine="Parent.AddView(LblNoeSabt,50%x,6%y,46%x,5%y)";
__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_lblnoesabt.getObject()),__c.PerXToCurrent((float) (50),ba),__c.PerYToCurrent((float) (6),ba),__c.PerXToCurrent((float) (46),ba),__c.PerYToCurrent((float) (5),ba));
RDebugUtils.currentLine=96993334;
 //BA.debugLineNum = 96993334;BA.debugLine="Dim LblNameBank As Label";
_lblnamebank = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96993335;
 //BA.debugLineNum = 96993335;BA.debugLine="LblNameBank.Initialize(\"LblNameBank\")";
_lblnamebank.Initialize(ba,"LblNameBank");
RDebugUtils.currentLine=96993336;
 //BA.debugLineNum = 96993336;BA.debugLine="LblNameBank.TextColor=Colors.Black";
_lblnamebank.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=96993337;
 //BA.debugLineNum = 96993337;BA.debugLine="LblNameBank.TextSize=16";
_lblnamebank.setTextSize((float) (16));
RDebugUtils.currentLine=96993338;
 //BA.debugLineNum = 96993338;BA.debugLine="LblNameBank.Gravity=Gravity.Right";
_lblnamebank.setGravity(__c.Gravity.RIGHT);
RDebugUtils.currentLine=96993339;
 //BA.debugLineNum = 96993339;BA.debugLine="LblNameBank.SingleLine=False";
_lblnamebank.setSingleLine(__c.False);
RDebugUtils.currentLine=96993340;
 //BA.debugLineNum = 96993340;BA.debugLine="LblNameBank.Typeface=MCode.Font2";
_lblnamebank.setTypeface((android.graphics.Typeface)(_mcode._font2 /*anywheresoftware.b4a.keywords.constants.TypefaceWrapper*/ .getObject()));
RDebugUtils.currentLine=96993341;
 //BA.debugLineNum = 96993341;BA.debugLine="LblNameBank.Color=Colors.Transparent";
_lblnamebank.setColor(__c.Colors.Transparent);
RDebugUtils.currentLine=96993342;
 //BA.debugLineNum = 96993342;BA.debugLine="Parent.AddView(LblNameBank,1%x,11%y,49%x,5%y)";
__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_lblnamebank.getObject()),__c.PerXToCurrent((float) (1),ba),__c.PerYToCurrent((float) (11),ba),__c.PerXToCurrent((float) (49),ba),__c.PerYToCurrent((float) (5),ba));
RDebugUtils.currentLine=96993344;
 //BA.debugLineNum = 96993344;BA.debugLine="Dim LblMablagh As Label";
_lblmablagh = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96993345;
 //BA.debugLineNum = 96993345;BA.debugLine="LblMablagh.Initialize(\"LblMablagh\")";
_lblmablagh.Initialize(ba,"LblMablagh");
RDebugUtils.currentLine=96993346;
 //BA.debugLineNum = 96993346;BA.debugLine="LblMablagh.TextColor=Colors.Black";
_lblmablagh.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=96993347;
 //BA.debugLineNum = 96993347;BA.debugLine="LblMablagh.TextSize=16";
_lblmablagh.setTextSize((float) (16));
RDebugUtils.currentLine=96993348;
 //BA.debugLineNum = 96993348;BA.debugLine="LblMablagh.Gravity=Gravity.Right";
_lblmablagh.setGravity(__c.Gravity.RIGHT);
RDebugUtils.currentLine=96993349;
 //BA.debugLineNum = 96993349;BA.debugLine="LblMablagh.SingleLine=False";
_lblmablagh.setSingleLine(__c.False);
RDebugUtils.currentLine=96993350;
 //BA.debugLineNum = 96993350;BA.debugLine="LblMablagh.Typeface=MCode.Font2";
_lblmablagh.setTypeface((android.graphics.Typeface)(_mcode._font2 /*anywheresoftware.b4a.keywords.constants.TypefaceWrapper*/ .getObject()));
RDebugUtils.currentLine=96993351;
 //BA.debugLineNum = 96993351;BA.debugLine="LblMablagh.Color=Colors.Transparent";
_lblmablagh.setColor(__c.Colors.Transparent);
RDebugUtils.currentLine=96993352;
 //BA.debugLineNum = 96993352;BA.debugLine="Parent.AddView(LblMablagh,50%x,11%y,46%x,5%y)";
__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_lblmablagh.getObject()),__c.PerXToCurrent((float) (50),ba),__c.PerYToCurrent((float) (11),ba),__c.PerXToCurrent((float) (46),ba),__c.PerYToCurrent((float) (5),ba));
RDebugUtils.currentLine=96993354;
 //BA.debugLineNum = 96993354;BA.debugLine="Dim LblShomareCheck As Label";
_lblshomarecheck = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96993355;
 //BA.debugLineNum = 96993355;BA.debugLine="LblShomareCheck.Initialize(\"LblShomareCheck\")";
_lblshomarecheck.Initialize(ba,"LblShomareCheck");
RDebugUtils.currentLine=96993356;
 //BA.debugLineNum = 96993356;BA.debugLine="LblShomareCheck.TextColor=Colors.Black";
_lblshomarecheck.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=96993357;
 //BA.debugLineNum = 96993357;BA.debugLine="LblShomareCheck.TextSize=16";
_lblshomarecheck.setTextSize((float) (16));
RDebugUtils.currentLine=96993358;
 //BA.debugLineNum = 96993358;BA.debugLine="LblShomareCheck.Gravity=Gravity.Right";
_lblshomarecheck.setGravity(__c.Gravity.RIGHT);
RDebugUtils.currentLine=96993359;
 //BA.debugLineNum = 96993359;BA.debugLine="LblShomareCheck.SingleLine=False";
_lblshomarecheck.setSingleLine(__c.False);
RDebugUtils.currentLine=96993360;
 //BA.debugLineNum = 96993360;BA.debugLine="LblShomareCheck.Typeface=MCode.Font2";
_lblshomarecheck.setTypeface((android.graphics.Typeface)(_mcode._font2 /*anywheresoftware.b4a.keywords.constants.TypefaceWrapper*/ .getObject()));
RDebugUtils.currentLine=96993361;
 //BA.debugLineNum = 96993361;BA.debugLine="LblShomareCheck.Color=Colors.Transparent";
_lblshomarecheck.setColor(__c.Colors.Transparent);
RDebugUtils.currentLine=96993362;
 //BA.debugLineNum = 96993362;BA.debugLine="Parent.AddView(LblShomareCheck,1%x,16%y,49%x,5%y)";
__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_lblshomarecheck.getObject()),__c.PerXToCurrent((float) (1),ba),__c.PerYToCurrent((float) (16),ba),__c.PerXToCurrent((float) (49),ba),__c.PerYToCurrent((float) (5),ba));
RDebugUtils.currentLine=96993364;
 //BA.debugLineNum = 96993364;BA.debugLine="Dim LblDateCheck As Label";
_lbldatecheck = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96993365;
 //BA.debugLineNum = 96993365;BA.debugLine="LblDateCheck.Initialize(\"LblDateCheck\")";
_lbldatecheck.Initialize(ba,"LblDateCheck");
RDebugUtils.currentLine=96993366;
 //BA.debugLineNum = 96993366;BA.debugLine="LblDateCheck.TextColor=Colors.Black";
_lbldatecheck.setTextColor(__c.Colors.Black);
RDebugUtils.currentLine=96993367;
 //BA.debugLineNum = 96993367;BA.debugLine="LblDateCheck.TextSize=16";
_lbldatecheck.setTextSize((float) (16));
RDebugUtils.currentLine=96993368;
 //BA.debugLineNum = 96993368;BA.debugLine="LblDateCheck.Gravity=Gravity.Right";
_lbldatecheck.setGravity(__c.Gravity.RIGHT);
RDebugUtils.currentLine=96993369;
 //BA.debugLineNum = 96993369;BA.debugLine="LblDateCheck.SingleLine=False";
_lbldatecheck.setSingleLine(__c.False);
RDebugUtils.currentLine=96993370;
 //BA.debugLineNum = 96993370;BA.debugLine="LblDateCheck.Typeface=MCode.Font2";
_lbldatecheck.setTypeface((android.graphics.Typeface)(_mcode._font2 /*anywheresoftware.b4a.keywords.constants.TypefaceWrapper*/ .getObject()));
RDebugUtils.currentLine=96993371;
 //BA.debugLineNum = 96993371;BA.debugLine="LblDateCheck.Color=Colors.Transparent";
_lbldatecheck.setColor(__c.Colors.Transparent);
RDebugUtils.currentLine=96993372;
 //BA.debugLineNum = 96993372;BA.debugLine="Parent.AddView(LblDateCheck,50%x,16%y,46%x,5%y)";
__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .AddView((android.view.View)(_lbldatecheck.getObject()),__c.PerXToCurrent((float) (50),ba),__c.PerYToCurrent((float) (16),ba),__c.PerXToCurrent((float) (46),ba),__c.PerYToCurrent((float) (5),ba));
RDebugUtils.currentLine=96993374;
 //BA.debugLineNum = 96993374;BA.debugLine="Dim Item As AdapterListSabt";
_item = new ir.parsikhesab.pakhsh.mcode._adapterlistsabt();
RDebugUtils.currentLine=96993375;
 //BA.debugLineNum = 96993375;BA.debugLine="Item.FldShomareSabt = cu.GetString(\"FldShomareSab";
_item.FldShomareSabt /*String*/  = _cu.GetString("FldShomareSabt");
RDebugUtils.currentLine=96993376;
 //BA.debugLineNum = 96993376;BA.debugLine="Item.FldC_Ashkhas = cu.GetString(\"FldC_Ashkhas\")";
_item.FldC_Ashkhas /*String*/  = _cu.GetString("FldC_Ashkhas");
RDebugUtils.currentLine=96993377;
 //BA.debugLineNum = 96993377;BA.debugLine="Item.FldType = cu.GetString(\"FldType\")";
_item.FldType /*String*/  = _cu.GetString("FldType");
RDebugUtils.currentLine=96993378;
 //BA.debugLineNum = 96993378;BA.debugLine="Item.FldNoe = cu.GetString(\"FldNoe\")";
_item.FldNoe /*String*/  = _cu.GetString("FldNoe");
RDebugUtils.currentLine=96993379;
 //BA.debugLineNum = 96993379;BA.debugLine="Item.FldMablagh = cu.GetString(\"FldMablagh\")";
_item.FldMablagh /*String*/  = _cu.GetString("FldMablagh");
RDebugUtils.currentLine=96993380;
 //BA.debugLineNum = 96993380;BA.debugLine="Item.FldShomareCheck = cu.GetString(\"FldShomareCh";
_item.FldShomareCheck /*String*/  = _cu.GetString("FldShomareCheck");
RDebugUtils.currentLine=96993381;
 //BA.debugLineNum = 96993381;BA.debugLine="Item.FldDateCheck = cu.GetString(\"FldDateCheck\")";
_item.FldDateCheck /*String*/  = _cu.GetString("FldDateCheck");
RDebugUtils.currentLine=96993382;
 //BA.debugLineNum = 96993382;BA.debugLine="Item.FldBankName = cu.GetString(\"FldBankName\")";
_item.FldBankName /*String*/  = _cu.GetString("FldBankName");
RDebugUtils.currentLine=96993383;
 //BA.debugLineNum = 96993383;BA.debugLine="Item.FldDateSabt = cu.GetString(\"FldDateSabt\")";
_item.FldDateSabt /*String*/  = _cu.GetString("FldDateSabt");
RDebugUtils.currentLine=96993385;
 //BA.debugLineNum = 96993385;BA.debugLine="Dim LblDateSabt As Label  = Parent.getview(0)";
_lbldatesabt = new anywheresoftware.b4a.objects.LabelWrapper();
_lbldatesabt = (anywheresoftware.b4a.objects.LabelWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.LabelWrapper(), (android.widget.TextView)(__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .GetView((int) (0)).getObject()));
RDebugUtils.currentLine=96993386;
 //BA.debugLineNum = 96993386;BA.debugLine="LblDateSabt.Text = \"تاریخ ثبت: \" & MCode.Sf.Mid(I";
_lbldatesabt.setText(BA.ObjectToCharSequence("تاریخ ثبت: "+_mcode._sf /*ADR.stringdemo.stringfunctions*/ ._vvv5(_item.FldDateSabt /*String*/ ,(int) (1),(int) (4))+"/"+_mcode._sf /*ADR.stringdemo.stringfunctions*/ ._vvv5(_item.FldDateSabt /*String*/ ,(int) (5),(int) (2))+"/"+_mcode._sf /*ADR.stringdemo.stringfunctions*/ ._vvv5(_item.FldDateSabt /*String*/ ,(int) (7),(int) (2))));
RDebugUtils.currentLine=96993388;
 //BA.debugLineNum = 96993388;BA.debugLine="Dim LblShomareSabt As Label  = Parent.getview(1)";
_lblshomaresabt = new anywheresoftware.b4a.objects.LabelWrapper();
_lblshomaresabt = (anywheresoftware.b4a.objects.LabelWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.LabelWrapper(), (android.widget.TextView)(__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .GetView((int) (1)).getObject()));
RDebugUtils.currentLine=96993389;
 //BA.debugLineNum = 96993389;BA.debugLine="LblShomareSabt.Text = \"شماره ثبت: \" & Item.FldSho";
_lblshomaresabt.setText(BA.ObjectToCharSequence("شماره ثبت: "+_item.FldShomareSabt /*String*/ ));
RDebugUtils.currentLine=96993391;
 //BA.debugLineNum = 96993391;BA.debugLine="Dim LblTypeSabt As Label  = Parent.getview(2)";
_lbltypesabt = new anywheresoftware.b4a.objects.LabelWrapper();
_lbltypesabt = (anywheresoftware.b4a.objects.LabelWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.LabelWrapper(), (android.widget.TextView)(__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .GetView((int) (2)).getObject()));
RDebugUtils.currentLine=96993392;
 //BA.debugLineNum = 96993392;BA.debugLine="Select Case Item.FldType";
switch (BA.switchObjectToInt(_item.FldType /*String*/ ,BA.NumberToString(1),BA.NumberToString(2))) {
case 0: {
RDebugUtils.currentLine=96993394;
 //BA.debugLineNum = 96993394;BA.debugLine="lblTitle.Text=\"رسید دریافت وجه\"";
__ref._lbltitle /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("رسید دریافت وجه"));
RDebugUtils.currentLine=96993395;
 //BA.debugLineNum = 96993395;BA.debugLine="LblTypeSabt.text = \"نوع تراکنش: دریافت\"";
_lbltypesabt.setText(BA.ObjectToCharSequence("نوع تراکنش: دریافت"));
 break; }
case 1: {
RDebugUtils.currentLine=96993397;
 //BA.debugLineNum = 96993397;BA.debugLine="lblTitle.Text=\"رسید پرداخت وجه\"";
__ref._lbltitle /*anywheresoftware.b4a.objects.LabelWrapper*/ .setText(BA.ObjectToCharSequence("رسید پرداخت وجه"));
RDebugUtils.currentLine=96993398;
 //BA.debugLineNum = 96993398;BA.debugLine="LblTypeSabt.text = \"نوع تراکنش: پرداخت\"";
_lbltypesabt.setText(BA.ObjectToCharSequence("نوع تراکنش: پرداخت"));
 break; }
}
;
RDebugUtils.currentLine=96993401;
 //BA.debugLineNum = 96993401;BA.debugLine="Dim LblNoeSabt As Label  = Parent.getview(3)";
_lblnoesabt = new anywheresoftware.b4a.objects.LabelWrapper();
_lblnoesabt = (anywheresoftware.b4a.objects.LabelWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.LabelWrapper(), (android.widget.TextView)(__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .GetView((int) (3)).getObject()));
RDebugUtils.currentLine=96993402;
 //BA.debugLineNum = 96993402;BA.debugLine="LblNoeSabt.text = \"نوع ثبت: \" & Item.FldNoe";
_lblnoesabt.setText(BA.ObjectToCharSequence("نوع ثبت: "+_item.FldNoe /*String*/ ));
RDebugUtils.currentLine=96993404;
 //BA.debugLineNum = 96993404;BA.debugLine="Dim LblNameBank As Label = Parent.getview(4)";
_lblnamebank = new anywheresoftware.b4a.objects.LabelWrapper();
_lblnamebank = (anywheresoftware.b4a.objects.LabelWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.LabelWrapper(), (android.widget.TextView)(__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .GetView((int) (4)).getObject()));
RDebugUtils.currentLine=96993405;
 //BA.debugLineNum = 96993405;BA.debugLine="If Item.FldBankName<>0 Then";
if ((_item.FldBankName /*String*/ ).equals(BA.NumberToString(0)) == false) { 
RDebugUtils.currentLine=96993406;
 //BA.debugLineNum = 96993406;BA.debugLine="LblNameBank.text = \"نام بانک: \" & Item.FldBankNa";
_lblnamebank.setText(BA.ObjectToCharSequence("نام بانک: "+_item.FldBankName /*String*/ ));
 }else {
RDebugUtils.currentLine=96993408;
 //BA.debugLineNum = 96993408;BA.debugLine="LblNameBank.text = \"نام بانک: -\"";
_lblnamebank.setText(BA.ObjectToCharSequence("نام بانک: -"));
 };
RDebugUtils.currentLine=96993411;
 //BA.debugLineNum = 96993411;BA.debugLine="Dim LblMablagh As Label = Parent.getview(5)";
_lblmablagh = new anywheresoftware.b4a.objects.LabelWrapper();
_lblmablagh = (anywheresoftware.b4a.objects.LabelWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.LabelWrapper(), (android.widget.TextView)(__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .GetView((int) (5)).getObject()));
RDebugUtils.currentLine=96993412;
 //BA.debugLineNum = 96993412;BA.debugLine="LblMablagh.text = \"مبلغ: \" & NumberFormat(Item.Fl";
_lblmablagh.setText(BA.ObjectToCharSequence("مبلغ: "+__c.NumberFormat((double)(Double.parseDouble(_item.FldMablagh /*String*/ )),(int) (1),(int) (3))));
RDebugUtils.currentLine=96993414;
 //BA.debugLineNum = 96993414;BA.debugLine="Dim LblShomareCheck As Label = Parent.getview(6)";
_lblshomarecheck = new anywheresoftware.b4a.objects.LabelWrapper();
_lblshomarecheck = (anywheresoftware.b4a.objects.LabelWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.LabelWrapper(), (android.widget.TextView)(__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .GetView((int) (6)).getObject()));
RDebugUtils.currentLine=96993415;
 //BA.debugLineNum = 96993415;BA.debugLine="If Item.FldShomareCheck <> 0 Then";
if ((_item.FldShomareCheck /*String*/ ).equals(BA.NumberToString(0)) == false) { 
RDebugUtils.currentLine=96993416;
 //BA.debugLineNum = 96993416;BA.debugLine="LblShomareCheck.text = \"شماره چک: \" & Item.FldSh";
_lblshomarecheck.setText(BA.ObjectToCharSequence("شماره چک: "+_item.FldShomareCheck /*String*/ ));
 }else {
RDebugUtils.currentLine=96993418;
 //BA.debugLineNum = 96993418;BA.debugLine="LblShomareCheck.text = \"شماره چک: -\"";
_lblshomarecheck.setText(BA.ObjectToCharSequence("شماره چک: -"));
 };
RDebugUtils.currentLine=96993420;
 //BA.debugLineNum = 96993420;BA.debugLine="Dim LblDateCheck As Label = Parent.getview(7)";
_lbldatecheck = new anywheresoftware.b4a.objects.LabelWrapper();
_lbldatecheck = (anywheresoftware.b4a.objects.LabelWrapper) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.LabelWrapper(), (android.widget.TextView)(__ref._parent /*anywheresoftware.b4a.objects.PanelWrapper*/ .GetView((int) (7)).getObject()));
RDebugUtils.currentLine=96993421;
 //BA.debugLineNum = 96993421;BA.debugLine="If Item.FldDateCheck <> 0 Then";
if ((_item.FldDateCheck /*String*/ ).equals(BA.NumberToString(0)) == false) { 
RDebugUtils.currentLine=96993422;
 //BA.debugLineNum = 96993422;BA.debugLine="LblDateCheck.text = \"تاریخ چک: \" & MCode.Sf.Mid(";
_lbldatecheck.setText(BA.ObjectToCharSequence("تاریخ چک: "+_mcode._sf /*ADR.stringdemo.stringfunctions*/ ._vvv5(_item.FldDateCheck /*String*/ ,(int) (1),(int) (4))+"/"+_mcode._sf /*ADR.stringdemo.stringfunctions*/ ._vvv5(_item.FldDateCheck /*String*/ ,(int) (5),(int) (2))+"/"+_mcode._sf /*ADR.stringdemo.stringfunctions*/ ._vvv5(_item.FldDateCheck /*String*/ ,(int) (7),(int) (2))));
 }else {
RDebugUtils.currentLine=96993424;
 //BA.debugLineNum = 96993424;BA.debugLine="LblDateCheck.text = \"تاریخ چک: -\"";
_lbldatecheck.setText(BA.ObjectToCharSequence("تاریخ چک: -"));
 };
RDebugUtils.currentLine=96993426;
 //BA.debugLineNum = 96993426;BA.debugLine="End Sub";
return "";
}
public anywheresoftware.b4a.objects.PanelWrapper  _getpanel(ir.parsikhesab.pakhsh.cls_printmali __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="cls_printmali";
if (Debug.shouldDelegate(ba, "getpanel", false))
	 {return ((anywheresoftware.b4a.objects.PanelWrapper) Debug.delegate(ba, "getpanel", null));}
RDebugUtils.currentLine=97058816;
 //BA.debugLineNum = 97058816;BA.debugLine="Public Sub getPanel As Panel";
RDebugUtils.currentLine=97058817;
 //BA.debugLineNum = 97058817;BA.debugLine="pnl_bk.RemoveView";
__ref._pnl_bk /*anywheresoftware.b4a.objects.PanelWrapper*/ .RemoveView();
RDebugUtils.currentLine=97058818;
 //BA.debugLineNum = 97058818;BA.debugLine="Return pnl_bk";
if (true) return __ref._pnl_bk /*anywheresoftware.b4a.objects.PanelWrapper*/ ;
RDebugUtils.currentLine=97058819;
 //BA.debugLineNum = 97058819;BA.debugLine="End Sub";
return null;
}
public String  _class_globals(ir.parsikhesab.pakhsh.cls_printmali __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="cls_printmali";
RDebugUtils.currentLine=96927744;
 //BA.debugLineNum = 96927744;BA.debugLine="Sub Class_Globals";
RDebugUtils.currentLine=96927745;
 //BA.debugLineNum = 96927745;BA.debugLine="Private p As Panel";
_p = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=96927746;
 //BA.debugLineNum = 96927746;BA.debugLine="Private pnl_bk As Panel";
_pnl_bk = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=96927748;
 //BA.debugLineNum = 96927748;BA.debugLine="Private lblTarikh As Label";
_lbltarikh = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96927749;
 //BA.debugLineNum = 96927749;BA.debugLine="Private LblNameMoshtari As Label";
_lblnamemoshtari = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96927750;
 //BA.debugLineNum = 96927750;BA.debugLine="Private lblAdress As Label";
_lbladress = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96927751;
 //BA.debugLineNum = 96927751;BA.debugLine="Private lblTel As Label";
_lbltel = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96927752;
 //BA.debugLineNum = 96927752;BA.debugLine="Private lblTitle As Label";
_lbltitle = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96927753;
 //BA.debugLineNum = 96927753;BA.debugLine="Private Parent As Panel";
_parent = new anywheresoftware.b4a.objects.PanelWrapper();
RDebugUtils.currentLine=96927754;
 //BA.debugLineNum = 96927754;BA.debugLine="Private Label1 As Label";
_label1 = new anywheresoftware.b4a.objects.LabelWrapper();
RDebugUtils.currentLine=96927755;
 //BA.debugLineNum = 96927755;BA.debugLine="End Sub";
return "";
}
public int  _getheight(ir.parsikhesab.pakhsh.cls_printmali __ref) throws Exception{
__ref = this;
RDebugUtils.currentModule="cls_printmali";
if (Debug.shouldDelegate(ba, "getheight", false))
	 {return ((Integer) Debug.delegate(ba, "getheight", null));}
RDebugUtils.currentLine=97124352;
 //BA.debugLineNum = 97124352;BA.debugLine="Public Sub getHeight As Int";
RDebugUtils.currentLine=97124353;
 //BA.debugLineNum = 97124353;BA.debugLine="Return pnl_bk.Height";
if (true) return __ref._pnl_bk /*anywheresoftware.b4a.objects.PanelWrapper*/ .getHeight();
RDebugUtils.currentLine=97124354;
 //BA.debugLineNum = 97124354;BA.debugLine="End Sub";
return 0;
}
}