
package ir.parsikhesab.pakhsh;

import anywheresoftware.b4a.pc.PCBA;
import anywheresoftware.b4a.pc.RemoteObject;

public class cl_appupdate {
    public static RemoteObject myClass;
	public cl_appupdate() {
	}
    public static PCBA staticBA = new PCBA(null, cl_appupdate.class);

public static RemoteObject __c = RemoteObject.declareNull("anywheresoftware.b4a.keywords.Common");
public static RemoteObject _err_nopkg = RemoteObject.createImmutable(0);
public static RemoteObject _err_notxt = RemoteObject.createImmutable(0);
public static RemoteObject _err_noapk = RemoteObject.createImmutable(0);
public static RemoteObject _err_txtrow = RemoteObject.createImmutable(0);
public static RemoteObject _err_html = RemoteObject.createImmutable(0);
public static RemoteObject _err_nospace = RemoteObject.createImmutable(0);
public static RemoteObject _err_noperm = RemoteObject.createImmutable(0);
public static RemoteObject _err_download = RemoteObject.createImmutable(0);
public static RemoteObject _err_http = RemoteObject.createImmutable(0);
public static RemoteObject _ok_init = RemoteObject.createImmutable(0);
public static RemoteObject _ok_curver = RemoteObject.createImmutable(0);
public static RemoteObject _ok_webver = RemoteObject.createImmutable(0);
public static RemoteObject _no_newerapk = RemoteObject.createImmutable(0);
public static RemoteObject _ok_newerapk = RemoteObject.createImmutable(0);
public static RemoteObject _ok_download = RemoteObject.createImmutable(0);
public static RemoteObject _ok_install = RemoteObject.createImmutable(0);
public static RemoteObject _callback = RemoteObject.declareNull("Object");
public static RemoteObject _event = RemoteObject.createImmutable("");
public static RemoteObject _spackagename = RemoteObject.createImmutable("");
public static RemoteObject _snewvertxt = RemoteObject.createImmutable("");
public static RemoteObject _snewverapk = RemoteObject.createImmutable("");
public static RemoteObject _sstatuscode = RemoteObject.createImmutable(0);
public static RemoteObject _susername = RemoteObject.createImmutable("");
public static RemoteObject _supassword = RemoteObject.createImmutable("");
public static RemoteObject _curver = RemoteObject.createImmutable("");
public static RemoteObject _webver = RemoteObject.createImmutable("");
public static RemoteObject _webclog = RemoteObject.createImmutable("");
public static RemoteObject _webfsize = RemoteObject.createImmutable("");
public static RemoteObject _sverbose = RemoteObject.createImmutable(false);
public static RemoteObject _pnlsplash = RemoteObject.declareNull("anywheresoftware.b4a.objects.PanelWrapper");
public static RemoteObject _splashshowing = RemoteObject.createImmutable(false);
public static RemoteObject _phone = RemoteObject.declareNull("anywheresoftware.b4a.phone.Phone");
public static RemoteObject _rp = RemoteObject.declareNull("anywheresoftware.b4a.objects.RuntimePermissions");
public static RemoteObject _sharedfolder = RemoteObject.createImmutable("");
public static RemoteObject _usefileprovider = RemoteObject.createImmutable(false);
public static RemoteObject _logcolor1 = RemoteObject.createImmutable(0);
public static RemoteObject _locationf = RemoteObject.declareNull("igolub.fused.b4a.location.android.location.LocationFWrapper.LocationFStatic");
public static RemoteObject _locationresult = RemoteObject.declareNull("igolub.fused.b4a.location.LocationResultWrapper.LocationResultConstants");
public static RemoteObject _locationrequest = RemoteObject.declareNull("igolub.fused.b4a.location.LocationRequestWrapper.LocationRequestConstants");
public static RemoteObject _priority = RemoteObject.declareNull("igolub.fused.b4a.location.staticmodules.PriorityWrapper");
public static RemoteObject _granularity = RemoteObject.declareNull("igolub.fused.b4a.location.staticmodules.GranularityWrapper");
public static RemoteObject _fileprovider = RemoteObject.declareNull("igolub.permissionmanager.b4a.PermissionsManagerFileProvider");
public static RemoteObject _permissionsmanager = RemoteObject.declareNull("igolub.permissionmanager.b4a.PermissionsManagerConstants");
public static RemoteObject _dateutils = RemoteObject.declareNull("b4a.example.dateutils");
public static ir.parsikhesab.pakhsh.main _main = null;
public static ir.parsikhesab.pakhsh.act_main _act_main = null;
public static ir.parsikhesab.pakhsh.service_server _service_server = null;
public static ir.parsikhesab.pakhsh.mcode _mcode = null;
public static ir.parsikhesab.pakhsh.mycode _mycode = null;
public static ir.parsikhesab.pakhsh.mdatabase _mdatabase = null;
public static ir.parsikhesab.pakhsh.gpswiget _gpswiget = null;
public static ir.parsikhesab.pakhsh.fusedlocationservice _fusedlocationservice = null;
public static ir.parsikhesab.pakhsh.service_helper _service_helper = null;
public static ir.parsikhesab.pakhsh.act_selectmantage _act_selectmantage = null;
public static ir.parsikhesab.pakhsh.act_reprizfactorvisitor _act_reprizfactorvisitor = null;
public static ir.parsikhesab.pakhsh.act_choose_report _act_choose_report = null;
public static ir.parsikhesab.pakhsh.act_emza _act_emza = null;
public static ir.parsikhesab.pakhsh.act_havaletozie _act_havaletozie = null;
public static ir.parsikhesab.pakhsh.act_imageslideshow _act_imageslideshow = null;
public static ir.parsikhesab.pakhsh.act_kala_listi _act_kala_listi = null;
public static ir.parsikhesab.pakhsh.act_kaladefault _act_kaladefault = null;
public static ir.parsikhesab.pakhsh.act_kalapaging _act_kalapaging = null;
public static ir.parsikhesab.pakhsh.act_kalapaging2 _act_kalapaging2 = null;
public static ir.parsikhesab.pakhsh.act_locationmoshtarian _act_locationmoshtarian = null;
public static ir.parsikhesab.pakhsh.act_locationvisitor _act_locationvisitor = null;
public static ir.parsikhesab.pakhsh.act_mali _act_mali = null;
public static ir.parsikhesab.pakhsh.act_moshtarian _act_moshtarian = null;
public static ir.parsikhesab.pakhsh.act_newashkhas _act_newashkhas = null;
public static ir.parsikhesab.pakhsh.act_notif _act_notif = null;
public static ir.parsikhesab.pakhsh.act_printmali _act_printmali = null;
public static ir.parsikhesab.pakhsh.act_printpic _act_printpic = null;
public static ir.parsikhesab.pakhsh.act_printpic2 _act_printpic2 = null;
public static ir.parsikhesab.pakhsh.act_profile _act_profile = null;
public static ir.parsikhesab.pakhsh.act_repfactors _act_repfactors = null;
public static ir.parsikhesab.pakhsh.act_repfactorvisitor _act_repfactorvisitor = null;
public static ir.parsikhesab.pakhsh.act_reportrizebargasht _act_reportrizebargasht = null;
public static ir.parsikhesab.pakhsh.act_reportsoorathesab _act_reportsoorathesab = null;
public static ir.parsikhesab.pakhsh.act_reportvisitor _act_reportvisitor = null;
public static ir.parsikhesab.pakhsh.act_reportvisitor2 _act_reportvisitor2 = null;
public static ir.parsikhesab.pakhsh.act_restore _act_restore = null;
public static ir.parsikhesab.pakhsh.act_rizefactorhavale _act_rizefactorhavale = null;
public static ir.parsikhesab.pakhsh.act_rizfaktor _act_rizfaktor = null;
public static ir.parsikhesab.pakhsh.act_rizhavale _act_rizhavale = null;
public static ir.parsikhesab.pakhsh.act_sabad _act_sabad = null;
public static ir.parsikhesab.pakhsh.act_sabtmarjooii _act_sabtmarjooii = null;
public static ir.parsikhesab.pakhsh.act_sabtrizcheck _act_sabtrizcheck = null;
public static ir.parsikhesab.pakhsh.act_saveinfocompany _act_saveinfocompany = null;
public static ir.parsikhesab.pakhsh.act_savelocation _act_savelocation = null;
public static ir.parsikhesab.pakhsh.act_search _act_search = null;
public static ir.parsikhesab.pakhsh.act_selfaktor _act_selfaktor = null;
public static ir.parsikhesab.pakhsh.act_senddata _act_senddata = null;
public static ir.parsikhesab.pakhsh.act_setting _act_setting = null;
public static ir.parsikhesab.pakhsh.act_settingpos _act_settingpos = null;
public static ir.parsikhesab.pakhsh.act_showlocation _act_showlocation = null;
public static ir.parsikhesab.pakhsh.act_support _act_support = null;
public static ir.parsikhesab.pakhsh.act_ticket _act_ticket = null;
public static ir.parsikhesab.pakhsh.act_video _act_video = null;
public static ir.parsikhesab.pakhsh.clskala _clskala = null;
public static ir.parsikhesab.pakhsh.dbutils _dbutils = null;
public static ir.parsikhesab.pakhsh.firebasemessaging _firebasemessaging = null;
public static ir.parsikhesab.pakhsh.geoservice _geoservice = null;
public static ir.parsikhesab.pakhsh.imagedownloader _imagedownloader = null;
public static ir.parsikhesab.pakhsh.myreceiver _myreceiver = null;
public static ir.parsikhesab.pakhsh.service_gps _service_gps = null;
public static ir.parsikhesab.pakhsh.service_notification _service_notification = null;
public static ir.parsikhesab.pakhsh.signaturecapture _signaturecapture = null;
public static ir.parsikhesab.pakhsh.starter _starter = null;
public static ir.parsikhesab.pakhsh.tracker _tracker = null;
public static ir.parsikhesab.pakhsh.wiget_service _wiget_service = null;
public static ir.parsikhesab.pakhsh.xmlviewex _xmlviewex = null;
public static ir.parsikhesab.pakhsh.newinst2 _newinst2 = null;
public static ir.parsikhesab.pakhsh.base64encodedecodeimage _base64encodedecodeimage = null;
public static ir.parsikhesab.pakhsh.httputils2service _httputils2service = null;
public static ir.parsikhesab.pakhsh.xuiviewsutils _xuiviewsutils = null;
public static Object[] GetGlobals(RemoteObject _ref) throws Exception {
		return new Object[] {"Callback",_ref.getField(false, "_callback"),"curver",_ref.getField(false, "_curver"),"DateUtils",_ref.getField(false, "_dateutils"),"ERR_DOWNLOAD",_ref.getField(false, "_err_download"),"ERR_HTML",_ref.getField(false, "_err_html"),"ERR_HTTP",_ref.getField(false, "_err_http"),"ERR_NOAPK",_ref.getField(false, "_err_noapk"),"ERR_NOPERM",_ref.getField(false, "_err_noperm"),"ERR_NOPKG",_ref.getField(false, "_err_nopkg"),"ERR_NOSPACE",_ref.getField(false, "_err_nospace"),"ERR_NOTXT",_ref.getField(false, "_err_notxt"),"ERR_TXTROW",_ref.getField(false, "_err_txtrow"),"Event",_ref.getField(false, "_event"),"FileProvider",_ref.getField(false, "_fileprovider"),"Granularity",_ref.getField(false, "_granularity"),"LocationF",_ref.getField(false, "_locationf"),"LocationRequest",_ref.getField(false, "_locationrequest"),"LocationResult",_ref.getField(false, "_locationresult"),"LogColor1",_ref.getField(false, "_logcolor1"),"NO_NEWERAPK",_ref.getField(false, "_no_newerapk"),"OK_CURVER",_ref.getField(false, "_ok_curver"),"OK_DOWNLOAD",_ref.getField(false, "_ok_download"),"OK_INIT",_ref.getField(false, "_ok_init"),"OK_INSTALL",_ref.getField(false, "_ok_install"),"OK_NEWERAPK",_ref.getField(false, "_ok_newerapk"),"OK_WEBVER",_ref.getField(false, "_ok_webver"),"PermissionsManager",_ref.getField(false, "_permissionsmanager"),"phone",_ref.getField(false, "_phone"),"pnlSplash",_ref.getField(false, "_pnlsplash"),"Priority",_ref.getField(false, "_priority"),"rp",_ref.getField(false, "_rp"),"SharedFolder",_ref.getField(false, "_sharedfolder"),"sNewVerApk",_ref.getField(false, "_snewverapk"),"sNewVerTxt",_ref.getField(false, "_snewvertxt"),"sPackageName",_ref.getField(false, "_spackagename"),"SplashShowing",_ref.getField(false, "_splashshowing"),"sStatusCode",_ref.getField(false, "_sstatuscode"),"sUPassword",_ref.getField(false, "_supassword"),"sUserName",_ref.getField(false, "_susername"),"sVerbose",_ref.getField(false, "_sverbose"),"UseFileProvider",_ref.getField(false, "_usefileprovider"),"webclog",_ref.getField(false, "_webclog"),"webfsize",_ref.getField(false, "_webfsize"),"webver",_ref.getField(false, "_webver")};
}
}