package ir.parsikhesab.pakhsh;

import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.pc.*;

public class cls_printmali_subs_0 {


public static RemoteObject  _class_globals(RemoteObject __ref) throws Exception{
 //BA.debugLineNum = 1;BA.debugLine="Sub Class_Globals";
 //BA.debugLineNum = 2;BA.debugLine="Private p As Panel";
cls_printmali._p = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");__ref.setField("_p",cls_printmali._p);
 //BA.debugLineNum = 3;BA.debugLine="Private pnl_bk As Panel";
cls_printmali._pnl_bk = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");__ref.setField("_pnl_bk",cls_printmali._pnl_bk);
 //BA.debugLineNum = 5;BA.debugLine="Private lblTarikh As Label";
cls_printmali._lbltarikh = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");__ref.setField("_lbltarikh",cls_printmali._lbltarikh);
 //BA.debugLineNum = 6;BA.debugLine="Private LblNameMoshtari As Label";
cls_printmali._lblnamemoshtari = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");__ref.setField("_lblnamemoshtari",cls_printmali._lblnamemoshtari);
 //BA.debugLineNum = 7;BA.debugLine="Private lblAdress As Label";
cls_printmali._lbladress = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");__ref.setField("_lbladress",cls_printmali._lbladress);
 //BA.debugLineNum = 8;BA.debugLine="Private lblTel As Label";
cls_printmali._lbltel = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");__ref.setField("_lbltel",cls_printmali._lbltel);
 //BA.debugLineNum = 9;BA.debugLine="Private lblTitle As Label";
cls_printmali._lbltitle = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");__ref.setField("_lbltitle",cls_printmali._lbltitle);
 //BA.debugLineNum = 10;BA.debugLine="Private Parent As Panel";
cls_printmali._parent = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");__ref.setField("_parent",cls_printmali._parent);
 //BA.debugLineNum = 11;BA.debugLine="Private Label1 As Label";
cls_printmali._label1 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");__ref.setField("_label1",cls_printmali._label1);
 //BA.debugLineNum = 12;BA.debugLine="End Sub";
return RemoteObject.createImmutable("");
}
public static RemoteObject  _getheight(RemoteObject __ref) throws Exception{
try {
		Debug.PushSubsStack("getHeight (cls_printmali) ","cls_printmali",72,__ref.getField(false, "ba"),__ref,168);
if (RapidSub.canDelegate("getheight")) { return __ref.runUserSub(false, "cls_printmali","getheight", __ref);}
 BA.debugLineNum = 168;BA.debugLine="Public Sub getHeight As Int";
Debug.ShouldStop(128);
 BA.debugLineNum = 169;BA.debugLine="Return pnl_bk.Height";
Debug.ShouldStop(256);
if (true) return __ref.getField(false,"_pnl_bk" /*RemoteObject*/ ).runMethod(true,"getHeight");
 BA.debugLineNum = 170;BA.debugLine="End Sub";
Debug.ShouldStop(512);
return RemoteObject.createImmutable(0);
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _getpanel(RemoteObject __ref) throws Exception{
try {
		Debug.PushSubsStack("getPanel (cls_printmali) ","cls_printmali",72,__ref.getField(false, "ba"),__ref,163);
if (RapidSub.canDelegate("getpanel")) { return __ref.runUserSub(false, "cls_printmali","getpanel", __ref);}
 BA.debugLineNum = 163;BA.debugLine="Public Sub getPanel As Panel";
Debug.ShouldStop(4);
 BA.debugLineNum = 164;BA.debugLine="pnl_bk.RemoveView";
Debug.ShouldStop(8);
__ref.getField(false,"_pnl_bk" /*RemoteObject*/ ).runVoidMethod ("RemoveView");
 BA.debugLineNum = 165;BA.debugLine="Return pnl_bk";
Debug.ShouldStop(16);
if (true) return __ref.getField(false,"_pnl_bk" /*RemoteObject*/ );
 BA.debugLineNum = 166;BA.debugLine="End Sub";
Debug.ShouldStop(32);
return RemoteObject.createImmutable(null);
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _initialize(RemoteObject __ref,RemoteObject _ba,RemoteObject _tarikh,RemoteObject _name,RemoteObject _address,RemoteObject _tel,RemoteObject _pardakhti,RemoteObject _cu) throws Exception{
try {
		Debug.PushSubsStack("Initialize (cls_printmali) ","cls_printmali",72,__ref.getField(false, "ba"),__ref,15);
if (RapidSub.canDelegate("initialize")) { return __ref.runUserSub(false, "cls_printmali","initialize", __ref, _ba, _tarikh, _name, _address, _tel, _pardakhti, _cu);}
__ref.runVoidMethodAndSync("innerInitializeHelper", _ba);
RemoteObject _lbldatesabt = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lblshomaresabt = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lbltypesabt = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lblnoesabt = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lblnamebank = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lblmablagh = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lblshomarecheck = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _lbldatecheck = RemoteObject.declareNull("anywheresoftware.b4a.objects.LabelWrapper");
RemoteObject _item = RemoteObject.declareNull("ir.parsikhesab.pakhsh.mcode._adapterlistsabt");
Debug.locals.put("ba", _ba);
Debug.locals.put("tarikh", _tarikh);
Debug.locals.put("name", _name);
Debug.locals.put("address", _address);
Debug.locals.put("tel", _tel);
Debug.locals.put("pardakhti", _pardakhti);
Debug.locals.put("cu", _cu);
 BA.debugLineNum = 15;BA.debugLine="Public Sub Initialize(tarikh As String,name As Str";
Debug.ShouldStop(16384);
 BA.debugLineNum = 16;BA.debugLine="p.Initialize(\"\")";
Debug.ShouldStop(32768);
__ref.getField(false,"_p" /*RemoteObject*/ ).runVoidMethod ("Initialize",__ref.getField(false, "ba"),(Object)(RemoteObject.createImmutable("")));
 BA.debugLineNum = 17;BA.debugLine="p.SetLayout(0,0,100%x,100%y)";
Debug.ShouldStop(65536);
__ref.getField(false,"_p" /*RemoteObject*/ ).runVoidMethod ("SetLayout",(Object)(BA.numberCast(int.class, 0)),(Object)(BA.numberCast(int.class, 0)),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 100)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 100)),__ref.getField(false, "ba"))));
 BA.debugLineNum = 18;BA.debugLine="p.LoadLayout(\"L_PrintMali\")";
Debug.ShouldStop(131072);
__ref.getField(false,"_p" /*RemoteObject*/ ).runMethodAndSync(false,"LoadLayout",(Object)(RemoteObject.createImmutable("L_PrintMali")),__ref.getField(false, "ba"));
 BA.debugLineNum = 19;BA.debugLine="lblAdress.Text=\"آدرس:\"&address";
Debug.ShouldStop(262144);
__ref.getField(false,"_lbladress" /*RemoteObject*/ ).runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("آدرس:"),_address)));
 BA.debugLineNum = 20;BA.debugLine="LblNameMoshtari.Text=\"نام مشتری:\"&name";
Debug.ShouldStop(524288);
__ref.getField(false,"_lblnamemoshtari" /*RemoteObject*/ ).runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("نام مشتری:"),_name)));
 BA.debugLineNum = 21;BA.debugLine="lblTarikh.Text=tarikh";
Debug.ShouldStop(1048576);
__ref.getField(false,"_lbltarikh" /*RemoteObject*/ ).runMethod(true,"setText",BA.ObjectToCharSequence(_tarikh));
 BA.debugLineNum = 22;BA.debugLine="lblTel.Text=\"تلفن:\"&tel";
Debug.ShouldStop(2097152);
__ref.getField(false,"_lbltel" /*RemoteObject*/ ).runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("تلفن:"),_tel)));
 BA.debugLineNum = 24;BA.debugLine="Label1.Text = MCode.AppName";
Debug.ShouldStop(8388608);
__ref.getField(false,"_label1" /*RemoteObject*/ ).runMethod(true,"setText",BA.ObjectToCharSequence(cls_printmali._mcode._appname /*RemoteObject*/ ));
 BA.debugLineNum = 27;BA.debugLine="cu.Position=0";
Debug.ShouldStop(67108864);
_cu.runMethod(true,"setPosition",BA.numberCast(int.class, 0));
 BA.debugLineNum = 29;BA.debugLine="Dim LblDateSabt As Label";
Debug.ShouldStop(268435456);
_lbldatesabt = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("LblDateSabt", _lbldatesabt);
 BA.debugLineNum = 30;BA.debugLine="LblDateSabt.Initialize(\"LblDateSabt\")";
Debug.ShouldStop(536870912);
_lbldatesabt.runVoidMethod ("Initialize",__ref.getField(false, "ba"),(Object)(RemoteObject.createImmutable("LblDateSabt")));
 BA.debugLineNum = 31;BA.debugLine="LblDateSabt.TextColor=Colors.Black";
Debug.ShouldStop(1073741824);
_lbldatesabt.runMethod(true,"setTextColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 32;BA.debugLine="LblDateSabt.TextSize=16";
Debug.ShouldStop(-2147483648);
_lbldatesabt.runMethod(true,"setTextSize",BA.numberCast(float.class, 16));
 BA.debugLineNum = 33;BA.debugLine="LblDateSabt.Gravity=Gravity.Right";
Debug.ShouldStop(1);
_lbldatesabt.runMethod(true,"setGravity",cls_printmali.__c.getField(false,"Gravity").getField(true,"RIGHT"));
 BA.debugLineNum = 34;BA.debugLine="LblDateSabt.SingleLine=False";
Debug.ShouldStop(2);
_lbldatesabt.runVoidMethod ("setSingleLine",cls_printmali.__c.getField(true,"False"));
 BA.debugLineNum = 35;BA.debugLine="LblDateSabt.Typeface=MCode.Font2";
Debug.ShouldStop(4);
_lbldatesabt.runMethod(false,"setTypeface",(cls_printmali._mcode._font2 /*RemoteObject*/ .getObject()));
 BA.debugLineNum = 36;BA.debugLine="LblDateSabt.Color=Colors.Transparent";
Debug.ShouldStop(8);
_lbldatesabt.runVoidMethod ("setColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Transparent"));
 BA.debugLineNum = 37;BA.debugLine="Parent.AddView(LblDateSabt,1%x,1%y,49%x,5%y)";
Debug.ShouldStop(16);
__ref.getField(false,"_parent" /*RemoteObject*/ ).runVoidMethod ("AddView",(Object)((_lbldatesabt.getObject())),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 1)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 1)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 49)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 5)),__ref.getField(false, "ba"))));
 BA.debugLineNum = 39;BA.debugLine="Dim LblShomareSabt As Label";
Debug.ShouldStop(64);
_lblshomaresabt = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("LblShomareSabt", _lblshomaresabt);
 BA.debugLineNum = 40;BA.debugLine="LblShomareSabt.Initialize(\"LblShomareSabt\")";
Debug.ShouldStop(128);
_lblshomaresabt.runVoidMethod ("Initialize",__ref.getField(false, "ba"),(Object)(RemoteObject.createImmutable("LblShomareSabt")));
 BA.debugLineNum = 41;BA.debugLine="LblShomareSabt.TextColor=Colors.Black";
Debug.ShouldStop(256);
_lblshomaresabt.runMethod(true,"setTextColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 42;BA.debugLine="LblShomareSabt.TextSize=16";
Debug.ShouldStop(512);
_lblshomaresabt.runMethod(true,"setTextSize",BA.numberCast(float.class, 16));
 BA.debugLineNum = 43;BA.debugLine="LblShomareSabt.Gravity=Gravity.Right";
Debug.ShouldStop(1024);
_lblshomaresabt.runMethod(true,"setGravity",cls_printmali.__c.getField(false,"Gravity").getField(true,"RIGHT"));
 BA.debugLineNum = 44;BA.debugLine="LblShomareSabt.SingleLine=False";
Debug.ShouldStop(2048);
_lblshomaresabt.runVoidMethod ("setSingleLine",cls_printmali.__c.getField(true,"False"));
 BA.debugLineNum = 45;BA.debugLine="LblShomareSabt.Typeface=MCode.Font2";
Debug.ShouldStop(4096);
_lblshomaresabt.runMethod(false,"setTypeface",(cls_printmali._mcode._font2 /*RemoteObject*/ .getObject()));
 BA.debugLineNum = 46;BA.debugLine="LblShomareSabt.Color=Colors.Transparent";
Debug.ShouldStop(8192);
_lblshomaresabt.runVoidMethod ("setColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Transparent"));
 BA.debugLineNum = 47;BA.debugLine="Parent.AddView(LblShomareSabt,50%x,1%y,46%x,5%y)";
Debug.ShouldStop(16384);
__ref.getField(false,"_parent" /*RemoteObject*/ ).runVoidMethod ("AddView",(Object)((_lblshomaresabt.getObject())),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 50)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 1)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 46)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 5)),__ref.getField(false, "ba"))));
 BA.debugLineNum = 49;BA.debugLine="Dim LblTypeSabt As Label";
Debug.ShouldStop(65536);
_lbltypesabt = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("LblTypeSabt", _lbltypesabt);
 BA.debugLineNum = 50;BA.debugLine="LblTypeSabt.Initialize(\"LblTypeSabt\")";
Debug.ShouldStop(131072);
_lbltypesabt.runVoidMethod ("Initialize",__ref.getField(false, "ba"),(Object)(RemoteObject.createImmutable("LblTypeSabt")));
 BA.debugLineNum = 51;BA.debugLine="LblTypeSabt.TextColor=Colors.Black";
Debug.ShouldStop(262144);
_lbltypesabt.runMethod(true,"setTextColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 52;BA.debugLine="LblTypeSabt.TextSize=16";
Debug.ShouldStop(524288);
_lbltypesabt.runMethod(true,"setTextSize",BA.numberCast(float.class, 16));
 BA.debugLineNum = 53;BA.debugLine="LblTypeSabt.Gravity=Gravity.Right";
Debug.ShouldStop(1048576);
_lbltypesabt.runMethod(true,"setGravity",cls_printmali.__c.getField(false,"Gravity").getField(true,"RIGHT"));
 BA.debugLineNum = 54;BA.debugLine="LblTypeSabt.SingleLine=False";
Debug.ShouldStop(2097152);
_lbltypesabt.runVoidMethod ("setSingleLine",cls_printmali.__c.getField(true,"False"));
 BA.debugLineNum = 55;BA.debugLine="LblTypeSabt.Typeface=MCode.Font2";
Debug.ShouldStop(4194304);
_lbltypesabt.runMethod(false,"setTypeface",(cls_printmali._mcode._font2 /*RemoteObject*/ .getObject()));
 BA.debugLineNum = 56;BA.debugLine="LblTypeSabt.Color=Colors.Transparent";
Debug.ShouldStop(8388608);
_lbltypesabt.runVoidMethod ("setColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Transparent"));
 BA.debugLineNum = 57;BA.debugLine="Parent.AddView(LblTypeSabt,1%x,6%y,49%x,5%y)";
Debug.ShouldStop(16777216);
__ref.getField(false,"_parent" /*RemoteObject*/ ).runVoidMethod ("AddView",(Object)((_lbltypesabt.getObject())),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 1)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 6)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 49)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 5)),__ref.getField(false, "ba"))));
 BA.debugLineNum = 59;BA.debugLine="Dim LblNoeSabt As Label";
Debug.ShouldStop(67108864);
_lblnoesabt = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("LblNoeSabt", _lblnoesabt);
 BA.debugLineNum = 60;BA.debugLine="LblNoeSabt.Initialize(\"LblNoeSabt\")";
Debug.ShouldStop(134217728);
_lblnoesabt.runVoidMethod ("Initialize",__ref.getField(false, "ba"),(Object)(RemoteObject.createImmutable("LblNoeSabt")));
 BA.debugLineNum = 61;BA.debugLine="LblNoeSabt.TextColor=Colors.Black";
Debug.ShouldStop(268435456);
_lblnoesabt.runMethod(true,"setTextColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 62;BA.debugLine="LblNoeSabt.TextSize=16";
Debug.ShouldStop(536870912);
_lblnoesabt.runMethod(true,"setTextSize",BA.numberCast(float.class, 16));
 BA.debugLineNum = 63;BA.debugLine="LblNoeSabt.Gravity=Gravity.Right";
Debug.ShouldStop(1073741824);
_lblnoesabt.runMethod(true,"setGravity",cls_printmali.__c.getField(false,"Gravity").getField(true,"RIGHT"));
 BA.debugLineNum = 64;BA.debugLine="LblNoeSabt.SingleLine=False";
Debug.ShouldStop(-2147483648);
_lblnoesabt.runVoidMethod ("setSingleLine",cls_printmali.__c.getField(true,"False"));
 BA.debugLineNum = 65;BA.debugLine="LblNoeSabt.Typeface=MCode.Font2";
Debug.ShouldStop(1);
_lblnoesabt.runMethod(false,"setTypeface",(cls_printmali._mcode._font2 /*RemoteObject*/ .getObject()));
 BA.debugLineNum = 66;BA.debugLine="LblNoeSabt.Color=Colors.Transparent";
Debug.ShouldStop(2);
_lblnoesabt.runVoidMethod ("setColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Transparent"));
 BA.debugLineNum = 67;BA.debugLine="Parent.AddView(LblNoeSabt,50%x,6%y,46%x,5%y)";
Debug.ShouldStop(4);
__ref.getField(false,"_parent" /*RemoteObject*/ ).runVoidMethod ("AddView",(Object)((_lblnoesabt.getObject())),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 50)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 6)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 46)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 5)),__ref.getField(false, "ba"))));
 BA.debugLineNum = 69;BA.debugLine="Dim LblNameBank As Label";
Debug.ShouldStop(16);
_lblnamebank = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("LblNameBank", _lblnamebank);
 BA.debugLineNum = 70;BA.debugLine="LblNameBank.Initialize(\"LblNameBank\")";
Debug.ShouldStop(32);
_lblnamebank.runVoidMethod ("Initialize",__ref.getField(false, "ba"),(Object)(RemoteObject.createImmutable("LblNameBank")));
 BA.debugLineNum = 71;BA.debugLine="LblNameBank.TextColor=Colors.Black";
Debug.ShouldStop(64);
_lblnamebank.runMethod(true,"setTextColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 72;BA.debugLine="LblNameBank.TextSize=16";
Debug.ShouldStop(128);
_lblnamebank.runMethod(true,"setTextSize",BA.numberCast(float.class, 16));
 BA.debugLineNum = 73;BA.debugLine="LblNameBank.Gravity=Gravity.Right";
Debug.ShouldStop(256);
_lblnamebank.runMethod(true,"setGravity",cls_printmali.__c.getField(false,"Gravity").getField(true,"RIGHT"));
 BA.debugLineNum = 74;BA.debugLine="LblNameBank.SingleLine=False";
Debug.ShouldStop(512);
_lblnamebank.runVoidMethod ("setSingleLine",cls_printmali.__c.getField(true,"False"));
 BA.debugLineNum = 75;BA.debugLine="LblNameBank.Typeface=MCode.Font2";
Debug.ShouldStop(1024);
_lblnamebank.runMethod(false,"setTypeface",(cls_printmali._mcode._font2 /*RemoteObject*/ .getObject()));
 BA.debugLineNum = 76;BA.debugLine="LblNameBank.Color=Colors.Transparent";
Debug.ShouldStop(2048);
_lblnamebank.runVoidMethod ("setColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Transparent"));
 BA.debugLineNum = 77;BA.debugLine="Parent.AddView(LblNameBank,1%x,11%y,49%x,5%y)";
Debug.ShouldStop(4096);
__ref.getField(false,"_parent" /*RemoteObject*/ ).runVoidMethod ("AddView",(Object)((_lblnamebank.getObject())),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 1)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 11)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 49)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 5)),__ref.getField(false, "ba"))));
 BA.debugLineNum = 79;BA.debugLine="Dim LblMablagh As Label";
Debug.ShouldStop(16384);
_lblmablagh = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("LblMablagh", _lblmablagh);
 BA.debugLineNum = 80;BA.debugLine="LblMablagh.Initialize(\"LblMablagh\")";
Debug.ShouldStop(32768);
_lblmablagh.runVoidMethod ("Initialize",__ref.getField(false, "ba"),(Object)(RemoteObject.createImmutable("LblMablagh")));
 BA.debugLineNum = 81;BA.debugLine="LblMablagh.TextColor=Colors.Black";
Debug.ShouldStop(65536);
_lblmablagh.runMethod(true,"setTextColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 82;BA.debugLine="LblMablagh.TextSize=16";
Debug.ShouldStop(131072);
_lblmablagh.runMethod(true,"setTextSize",BA.numberCast(float.class, 16));
 BA.debugLineNum = 83;BA.debugLine="LblMablagh.Gravity=Gravity.Right";
Debug.ShouldStop(262144);
_lblmablagh.runMethod(true,"setGravity",cls_printmali.__c.getField(false,"Gravity").getField(true,"RIGHT"));
 BA.debugLineNum = 84;BA.debugLine="LblMablagh.SingleLine=False";
Debug.ShouldStop(524288);
_lblmablagh.runVoidMethod ("setSingleLine",cls_printmali.__c.getField(true,"False"));
 BA.debugLineNum = 85;BA.debugLine="LblMablagh.Typeface=MCode.Font2";
Debug.ShouldStop(1048576);
_lblmablagh.runMethod(false,"setTypeface",(cls_printmali._mcode._font2 /*RemoteObject*/ .getObject()));
 BA.debugLineNum = 86;BA.debugLine="LblMablagh.Color=Colors.Transparent";
Debug.ShouldStop(2097152);
_lblmablagh.runVoidMethod ("setColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Transparent"));
 BA.debugLineNum = 87;BA.debugLine="Parent.AddView(LblMablagh,50%x,11%y,46%x,5%y)";
Debug.ShouldStop(4194304);
__ref.getField(false,"_parent" /*RemoteObject*/ ).runVoidMethod ("AddView",(Object)((_lblmablagh.getObject())),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 50)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 11)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 46)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 5)),__ref.getField(false, "ba"))));
 BA.debugLineNum = 89;BA.debugLine="Dim LblShomareCheck As Label";
Debug.ShouldStop(16777216);
_lblshomarecheck = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("LblShomareCheck", _lblshomarecheck);
 BA.debugLineNum = 90;BA.debugLine="LblShomareCheck.Initialize(\"LblShomareCheck\")";
Debug.ShouldStop(33554432);
_lblshomarecheck.runVoidMethod ("Initialize",__ref.getField(false, "ba"),(Object)(RemoteObject.createImmutable("LblShomareCheck")));
 BA.debugLineNum = 91;BA.debugLine="LblShomareCheck.TextColor=Colors.Black";
Debug.ShouldStop(67108864);
_lblshomarecheck.runMethod(true,"setTextColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 92;BA.debugLine="LblShomareCheck.TextSize=16";
Debug.ShouldStop(134217728);
_lblshomarecheck.runMethod(true,"setTextSize",BA.numberCast(float.class, 16));
 BA.debugLineNum = 93;BA.debugLine="LblShomareCheck.Gravity=Gravity.Right";
Debug.ShouldStop(268435456);
_lblshomarecheck.runMethod(true,"setGravity",cls_printmali.__c.getField(false,"Gravity").getField(true,"RIGHT"));
 BA.debugLineNum = 94;BA.debugLine="LblShomareCheck.SingleLine=False";
Debug.ShouldStop(536870912);
_lblshomarecheck.runVoidMethod ("setSingleLine",cls_printmali.__c.getField(true,"False"));
 BA.debugLineNum = 95;BA.debugLine="LblShomareCheck.Typeface=MCode.Font2";
Debug.ShouldStop(1073741824);
_lblshomarecheck.runMethod(false,"setTypeface",(cls_printmali._mcode._font2 /*RemoteObject*/ .getObject()));
 BA.debugLineNum = 96;BA.debugLine="LblShomareCheck.Color=Colors.Transparent";
Debug.ShouldStop(-2147483648);
_lblshomarecheck.runVoidMethod ("setColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Transparent"));
 BA.debugLineNum = 97;BA.debugLine="Parent.AddView(LblShomareCheck,1%x,16%y,49%x,5%y)";
Debug.ShouldStop(1);
__ref.getField(false,"_parent" /*RemoteObject*/ ).runVoidMethod ("AddView",(Object)((_lblshomarecheck.getObject())),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 1)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 16)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 49)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 5)),__ref.getField(false, "ba"))));
 BA.debugLineNum = 99;BA.debugLine="Dim LblDateCheck As Label";
Debug.ShouldStop(4);
_lbldatecheck = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");Debug.locals.put("LblDateCheck", _lbldatecheck);
 BA.debugLineNum = 100;BA.debugLine="LblDateCheck.Initialize(\"LblDateCheck\")";
Debug.ShouldStop(8);
_lbldatecheck.runVoidMethod ("Initialize",__ref.getField(false, "ba"),(Object)(RemoteObject.createImmutable("LblDateCheck")));
 BA.debugLineNum = 101;BA.debugLine="LblDateCheck.TextColor=Colors.Black";
Debug.ShouldStop(16);
_lbldatecheck.runMethod(true,"setTextColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Black"));
 BA.debugLineNum = 102;BA.debugLine="LblDateCheck.TextSize=16";
Debug.ShouldStop(32);
_lbldatecheck.runMethod(true,"setTextSize",BA.numberCast(float.class, 16));
 BA.debugLineNum = 103;BA.debugLine="LblDateCheck.Gravity=Gravity.Right";
Debug.ShouldStop(64);
_lbldatecheck.runMethod(true,"setGravity",cls_printmali.__c.getField(false,"Gravity").getField(true,"RIGHT"));
 BA.debugLineNum = 104;BA.debugLine="LblDateCheck.SingleLine=False";
Debug.ShouldStop(128);
_lbldatecheck.runVoidMethod ("setSingleLine",cls_printmali.__c.getField(true,"False"));
 BA.debugLineNum = 105;BA.debugLine="LblDateCheck.Typeface=MCode.Font2";
Debug.ShouldStop(256);
_lbldatecheck.runMethod(false,"setTypeface",(cls_printmali._mcode._font2 /*RemoteObject*/ .getObject()));
 BA.debugLineNum = 106;BA.debugLine="LblDateCheck.Color=Colors.Transparent";
Debug.ShouldStop(512);
_lbldatecheck.runVoidMethod ("setColor",cls_printmali.__c.getField(false,"Colors").getField(true,"Transparent"));
 BA.debugLineNum = 107;BA.debugLine="Parent.AddView(LblDateCheck,50%x,16%y,46%x,5%y)";
Debug.ShouldStop(1024);
__ref.getField(false,"_parent" /*RemoteObject*/ ).runVoidMethod ("AddView",(Object)((_lbldatecheck.getObject())),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 50)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 16)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerXToCurrent",(Object)(BA.numberCast(float.class, 46)),__ref.getField(false, "ba"))),(Object)(cls_printmali.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 5)),__ref.getField(false, "ba"))));
 BA.debugLineNum = 109;BA.debugLine="Dim Item As AdapterListSabt";
Debug.ShouldStop(4096);
_item = RemoteObject.createNew ("ir.parsikhesab.pakhsh.mcode._adapterlistsabt");Debug.locals.put("Item", _item);
 BA.debugLineNum = 110;BA.debugLine="Item.FldShomareSabt = cu.GetString(\"FldShomareSab";
Debug.ShouldStop(8192);
_item.setField ("FldShomareSabt" /*RemoteObject*/ ,_cu.runMethod(true,"GetString",(Object)(RemoteObject.createImmutable("FldShomareSabt"))));
 BA.debugLineNum = 111;BA.debugLine="Item.FldC_Ashkhas = cu.GetString(\"FldC_Ashkhas\")";
Debug.ShouldStop(16384);
_item.setField ("FldC_Ashkhas" /*RemoteObject*/ ,_cu.runMethod(true,"GetString",(Object)(RemoteObject.createImmutable("FldC_Ashkhas"))));
 BA.debugLineNum = 112;BA.debugLine="Item.FldType = cu.GetString(\"FldType\")";
Debug.ShouldStop(32768);
_item.setField ("FldType" /*RemoteObject*/ ,_cu.runMethod(true,"GetString",(Object)(RemoteObject.createImmutable("FldType"))));
 BA.debugLineNum = 113;BA.debugLine="Item.FldNoe = cu.GetString(\"FldNoe\")";
Debug.ShouldStop(65536);
_item.setField ("FldNoe" /*RemoteObject*/ ,_cu.runMethod(true,"GetString",(Object)(RemoteObject.createImmutable("FldNoe"))));
 BA.debugLineNum = 114;BA.debugLine="Item.FldMablagh = cu.GetString(\"FldMablagh\")";
Debug.ShouldStop(131072);
_item.setField ("FldMablagh" /*RemoteObject*/ ,_cu.runMethod(true,"GetString",(Object)(RemoteObject.createImmutable("FldMablagh"))));
 BA.debugLineNum = 115;BA.debugLine="Item.FldShomareCheck = cu.GetString(\"FldShomareCh";
Debug.ShouldStop(262144);
_item.setField ("FldShomareCheck" /*RemoteObject*/ ,_cu.runMethod(true,"GetString",(Object)(RemoteObject.createImmutable("FldShomareCheck"))));
 BA.debugLineNum = 116;BA.debugLine="Item.FldDateCheck = cu.GetString(\"FldDateCheck\")";
Debug.ShouldStop(524288);
_item.setField ("FldDateCheck" /*RemoteObject*/ ,_cu.runMethod(true,"GetString",(Object)(RemoteObject.createImmutable("FldDateCheck"))));
 BA.debugLineNum = 117;BA.debugLine="Item.FldBankName = cu.GetString(\"FldBankName\")";
Debug.ShouldStop(1048576);
_item.setField ("FldBankName" /*RemoteObject*/ ,_cu.runMethod(true,"GetString",(Object)(RemoteObject.createImmutable("FldBankName"))));
 BA.debugLineNum = 118;BA.debugLine="Item.FldDateSabt = cu.GetString(\"FldDateSabt\")";
Debug.ShouldStop(2097152);
_item.setField ("FldDateSabt" /*RemoteObject*/ ,_cu.runMethod(true,"GetString",(Object)(RemoteObject.createImmutable("FldDateSabt"))));
 BA.debugLineNum = 120;BA.debugLine="Dim LblDateSabt As Label  = Parent.getview(0)";
Debug.ShouldStop(8388608);
_lbldatesabt = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
_lbldatesabt = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.LabelWrapper"), __ref.getField(false,"_parent" /*RemoteObject*/ ).runMethod(false,"GetView",(Object)(BA.numberCast(int.class, 0))).getObject());Debug.locals.put("LblDateSabt", _lbldatesabt);Debug.locals.put("LblDateSabt", _lbldatesabt);
 BA.debugLineNum = 121;BA.debugLine="LblDateSabt.Text = \"تاریخ ثبت: \" & MCode.Sf.Mid(I";
Debug.ShouldStop(16777216);
_lbldatesabt.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("تاریخ ثبت: "),cls_printmali._mcode._sf /*RemoteObject*/ .runMethod(true,"_vvv5",(Object)(_item.getField(true,"FldDateSabt" /*RemoteObject*/ )),(Object)(BA.numberCast(int.class, 1)),(Object)(BA.numberCast(int.class, 4))),RemoteObject.createImmutable("/"),cls_printmali._mcode._sf /*RemoteObject*/ .runMethod(true,"_vvv5",(Object)(_item.getField(true,"FldDateSabt" /*RemoteObject*/ )),(Object)(BA.numberCast(int.class, 5)),(Object)(BA.numberCast(int.class, 2))),RemoteObject.createImmutable("/"),cls_printmali._mcode._sf /*RemoteObject*/ .runMethod(true,"_vvv5",(Object)(_item.getField(true,"FldDateSabt" /*RemoteObject*/ )),(Object)(BA.numberCast(int.class, 7)),(Object)(BA.numberCast(int.class, 2))))));
 BA.debugLineNum = 123;BA.debugLine="Dim LblShomareSabt As Label  = Parent.getview(1)";
Debug.ShouldStop(67108864);
_lblshomaresabt = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
_lblshomaresabt = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.LabelWrapper"), __ref.getField(false,"_parent" /*RemoteObject*/ ).runMethod(false,"GetView",(Object)(BA.numberCast(int.class, 1))).getObject());Debug.locals.put("LblShomareSabt", _lblshomaresabt);Debug.locals.put("LblShomareSabt", _lblshomaresabt);
 BA.debugLineNum = 124;BA.debugLine="LblShomareSabt.Text = \"شماره ثبت: \" & Item.FldSho";
Debug.ShouldStop(134217728);
_lblshomaresabt.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("شماره ثبت: "),_item.getField(true,"FldShomareSabt" /*RemoteObject*/ ))));
 BA.debugLineNum = 126;BA.debugLine="Dim LblTypeSabt As Label  = Parent.getview(2)";
Debug.ShouldStop(536870912);
_lbltypesabt = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
_lbltypesabt = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.LabelWrapper"), __ref.getField(false,"_parent" /*RemoteObject*/ ).runMethod(false,"GetView",(Object)(BA.numberCast(int.class, 2))).getObject());Debug.locals.put("LblTypeSabt", _lbltypesabt);Debug.locals.put("LblTypeSabt", _lbltypesabt);
 BA.debugLineNum = 127;BA.debugLine="Select Case Item.FldType";
Debug.ShouldStop(1073741824);
switch (BA.switchObjectToInt(_item.getField(true,"FldType" /*RemoteObject*/ ),BA.NumberToString(1),BA.NumberToString(2))) {
case 0: {
 BA.debugLineNum = 129;BA.debugLine="lblTitle.Text=\"رسید دریافت وجه\"";
Debug.ShouldStop(1);
__ref.getField(false,"_lbltitle" /*RemoteObject*/ ).runMethod(true,"setText",BA.ObjectToCharSequence("رسید دریافت وجه"));
 BA.debugLineNum = 130;BA.debugLine="LblTypeSabt.text = \"نوع تراکنش: دریافت\"";
Debug.ShouldStop(2);
_lbltypesabt.runMethod(true,"setText",BA.ObjectToCharSequence("نوع تراکنش: دریافت"));
 break; }
case 1: {
 BA.debugLineNum = 132;BA.debugLine="lblTitle.Text=\"رسید پرداخت وجه\"";
Debug.ShouldStop(8);
__ref.getField(false,"_lbltitle" /*RemoteObject*/ ).runMethod(true,"setText",BA.ObjectToCharSequence("رسید پرداخت وجه"));
 BA.debugLineNum = 133;BA.debugLine="LblTypeSabt.text = \"نوع تراکنش: پرداخت\"";
Debug.ShouldStop(16);
_lbltypesabt.runMethod(true,"setText",BA.ObjectToCharSequence("نوع تراکنش: پرداخت"));
 break; }
}
;
 BA.debugLineNum = 136;BA.debugLine="Dim LblNoeSabt As Label  = Parent.getview(3)";
Debug.ShouldStop(128);
_lblnoesabt = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
_lblnoesabt = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.LabelWrapper"), __ref.getField(false,"_parent" /*RemoteObject*/ ).runMethod(false,"GetView",(Object)(BA.numberCast(int.class, 3))).getObject());Debug.locals.put("LblNoeSabt", _lblnoesabt);Debug.locals.put("LblNoeSabt", _lblnoesabt);
 BA.debugLineNum = 137;BA.debugLine="LblNoeSabt.text = \"نوع ثبت: \" & Item.FldNoe";
Debug.ShouldStop(256);
_lblnoesabt.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("نوع ثبت: "),_item.getField(true,"FldNoe" /*RemoteObject*/ ))));
 BA.debugLineNum = 139;BA.debugLine="Dim LblNameBank As Label = Parent.getview(4)";
Debug.ShouldStop(1024);
_lblnamebank = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
_lblnamebank = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.LabelWrapper"), __ref.getField(false,"_parent" /*RemoteObject*/ ).runMethod(false,"GetView",(Object)(BA.numberCast(int.class, 4))).getObject());Debug.locals.put("LblNameBank", _lblnamebank);Debug.locals.put("LblNameBank", _lblnamebank);
 BA.debugLineNum = 140;BA.debugLine="If Item.FldBankName<>0 Then";
Debug.ShouldStop(2048);
if (RemoteObject.solveBoolean("!",_item.getField(true,"FldBankName" /*RemoteObject*/ ),BA.NumberToString(0))) { 
 BA.debugLineNum = 141;BA.debugLine="LblNameBank.text = \"نام بانک: \" & Item.FldBankNa";
Debug.ShouldStop(4096);
_lblnamebank.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("نام بانک: "),_item.getField(true,"FldBankName" /*RemoteObject*/ ))));
 }else {
 BA.debugLineNum = 143;BA.debugLine="LblNameBank.text = \"نام بانک: -\"";
Debug.ShouldStop(16384);
_lblnamebank.runMethod(true,"setText",BA.ObjectToCharSequence("نام بانک: -"));
 };
 BA.debugLineNum = 146;BA.debugLine="Dim LblMablagh As Label = Parent.getview(5)";
Debug.ShouldStop(131072);
_lblmablagh = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
_lblmablagh = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.LabelWrapper"), __ref.getField(false,"_parent" /*RemoteObject*/ ).runMethod(false,"GetView",(Object)(BA.numberCast(int.class, 5))).getObject());Debug.locals.put("LblMablagh", _lblmablagh);Debug.locals.put("LblMablagh", _lblmablagh);
 BA.debugLineNum = 147;BA.debugLine="LblMablagh.text = \"مبلغ: \" & NumberFormat(Item.Fl";
Debug.ShouldStop(262144);
_lblmablagh.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("مبلغ: "),cls_printmali.__c.runMethod(true,"NumberFormat",(Object)(BA.numberCast(double.class, _item.getField(true,"FldMablagh" /*RemoteObject*/ ))),(Object)(BA.numberCast(int.class, 1)),(Object)(BA.numberCast(int.class, 3))))));
 BA.debugLineNum = 149;BA.debugLine="Dim LblShomareCheck As Label = Parent.getview(6)";
Debug.ShouldStop(1048576);
_lblshomarecheck = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
_lblshomarecheck = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.LabelWrapper"), __ref.getField(false,"_parent" /*RemoteObject*/ ).runMethod(false,"GetView",(Object)(BA.numberCast(int.class, 6))).getObject());Debug.locals.put("LblShomareCheck", _lblshomarecheck);Debug.locals.put("LblShomareCheck", _lblshomarecheck);
 BA.debugLineNum = 150;BA.debugLine="If Item.FldShomareCheck <> 0 Then";
Debug.ShouldStop(2097152);
if (RemoteObject.solveBoolean("!",_item.getField(true,"FldShomareCheck" /*RemoteObject*/ ),BA.NumberToString(0))) { 
 BA.debugLineNum = 151;BA.debugLine="LblShomareCheck.text = \"شماره چک: \" & Item.FldSh";
Debug.ShouldStop(4194304);
_lblshomarecheck.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("شماره چک: "),_item.getField(true,"FldShomareCheck" /*RemoteObject*/ ))));
 }else {
 BA.debugLineNum = 153;BA.debugLine="LblShomareCheck.text = \"شماره چک: -\"";
Debug.ShouldStop(16777216);
_lblshomarecheck.runMethod(true,"setText",BA.ObjectToCharSequence("شماره چک: -"));
 };
 BA.debugLineNum = 155;BA.debugLine="Dim LblDateCheck As Label = Parent.getview(7)";
Debug.ShouldStop(67108864);
_lbldatecheck = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
_lbldatecheck = RemoteObject.declareNull("anywheresoftware.b4a.AbsObjectWrapper").runMethod(false, "ConvertToWrapper", RemoteObject.createNew("anywheresoftware.b4a.objects.LabelWrapper"), __ref.getField(false,"_parent" /*RemoteObject*/ ).runMethod(false,"GetView",(Object)(BA.numberCast(int.class, 7))).getObject());Debug.locals.put("LblDateCheck", _lbldatecheck);Debug.locals.put("LblDateCheck", _lbldatecheck);
 BA.debugLineNum = 156;BA.debugLine="If Item.FldDateCheck <> 0 Then";
Debug.ShouldStop(134217728);
if (RemoteObject.solveBoolean("!",_item.getField(true,"FldDateCheck" /*RemoteObject*/ ),BA.NumberToString(0))) { 
 BA.debugLineNum = 157;BA.debugLine="LblDateCheck.text = \"تاریخ چک: \" & MCode.Sf.Mid(";
Debug.ShouldStop(268435456);
_lbldatecheck.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("تاریخ چک: "),cls_printmali._mcode._sf /*RemoteObject*/ .runMethod(true,"_vvv5",(Object)(_item.getField(true,"FldDateCheck" /*RemoteObject*/ )),(Object)(BA.numberCast(int.class, 1)),(Object)(BA.numberCast(int.class, 4))),RemoteObject.createImmutable("/"),cls_printmali._mcode._sf /*RemoteObject*/ .runMethod(true,"_vvv5",(Object)(_item.getField(true,"FldDateCheck" /*RemoteObject*/ )),(Object)(BA.numberCast(int.class, 5)),(Object)(BA.numberCast(int.class, 2))),RemoteObject.createImmutable("/"),cls_printmali._mcode._sf /*RemoteObject*/ .runMethod(true,"_vvv5",(Object)(_item.getField(true,"FldDateCheck" /*RemoteObject*/ )),(Object)(BA.numberCast(int.class, 7)),(Object)(BA.numberCast(int.class, 2))))));
 }else {
 BA.debugLineNum = 159;BA.debugLine="LblDateCheck.text = \"تاریخ چک: -\"";
Debug.ShouldStop(1073741824);
_lbldatecheck.runMethod(true,"setText",BA.ObjectToCharSequence("تاریخ چک: -"));
 };
 BA.debugLineNum = 161;BA.debugLine="End Sub";
Debug.ShouldStop(1);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
}