
package ir.parsikhesab.pakhsh;

import java.io.IOException;
import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.pc.PCBA;
import anywheresoftware.b4a.pc.RDebug;
import anywheresoftware.b4a.pc.RemoteObject;
import anywheresoftware.b4a.pc.RDebug.IRemote;
import anywheresoftware.b4a.pc.Debug;
import anywheresoftware.b4a.pc.B4XTypes.B4XClass;
import anywheresoftware.b4a.pc.B4XTypes.DeviceClass;

public class mcode implements IRemote{
	public static mcode mostCurrent;
	public static RemoteObject processBA;
    public static boolean processGlobalsRun;
    public static RemoteObject myClass;
    public static RemoteObject remoteMe;
	public mcode() {
		mostCurrent = this;
	}
    public RemoteObject getRemoteMe() {
        return remoteMe;    
    }
    
public boolean isSingleton() {
		return true;
	}
     private static PCBA pcBA = new PCBA(null, mcode.class);
    static {
		mostCurrent = new mcode();
        remoteMe = RemoteObject.declareNull("ir.parsikhesab.pakhsh.mcode");
        anywheresoftware.b4a.pc.RapidSub.moduleToObject.put(new B4XClass("mcode"), "ir.parsikhesab.pakhsh.mcode");
        RDebug.INSTANCE.eventTargets.put(new DeviceClass("ir.parsikhesab.pakhsh.mcode"), new java.lang.ref.WeakReference<PCBA> (pcBA));
	}
   
	public static RemoteObject runMethod(boolean notUsed, String method, Object... args) throws Exception{
		return (RemoteObject) pcBA.raiseEvent(method.substring(1), args);
	}
    public static void runVoidMethod(String method, Object... args) throws Exception{
		runMethod(false, method, args);
	}
	public PCBA create(Object[] args) throws ClassNotFoundException{
        throw new RuntimeException("CREATE is not supported.");
	}
public static RemoteObject __c = RemoteObject.declareNull("anywheresoftware.b4a.keywords.Common");
public static RemoteObject _sql1 = RemoteObject.declareNull("anywheresoftware.b4a.sql.SQL");
public static RemoteObject _sf = RemoteObject.declareNull("ADR.stringdemo.stringfunctions");
public static RemoteObject _iconview = RemoteObject.declareNull("ir.aghajari.iconanim.Amir_IconView");
public static RemoteObject _persiandate = RemoteObject.declareNull("anywheresoftware.b4a.student.PersianDate");
public static RemoteObject _md = RemoteObject.declareNull("com.maximussoft.msmaterialdrawer.MSMaterialDrawer");
public static RemoteObject _json = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.JSONParser");
public static RemoteObject _jsong = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.JSONParser.JSONGenerator");
public static RemoteObject _p = RemoteObject.declareNull("anywheresoftware.b4a.phone.Phone.PhoneId");
public static RemoteObject _pimei = RemoteObject.declareNull("anywheresoftware.b4a.phone.Phone");
public static RemoteObject _imei = RemoteObject.declareNull("anywheresoftware.b4a.phone.Phone.PhoneId");
public static RemoteObject _strimei = RemoteObject.createImmutable("");
public static RemoteObject _font2 = RemoteObject.declareNull("anywheresoftware.b4a.keywords.constants.TypefaceWrapper");
public static RemoteObject _placeholder = RemoteObject.declareNull("anywheresoftware.b4a.objects.drawable.CanvasWrapper.BitmapWrapper");
public static RemoteObject _vahedpool = RemoteObject.createImmutable("");
public static RemoteObject _raghamashar = RemoteObject.createImmutable("");
public static RemoteObject _c_visitor = RemoteObject.createImmutable("");
public static RemoteObject _n_visitor = RemoteObject.createImmutable("");
public static RemoteObject _url = RemoteObject.createImmutable("");
public static RemoteObject _kalamanfi = RemoteObject.createImmutable("");
public static RemoteObject _taghirfeekala = RemoteObject.createImmutable("");
public static RemoteObject _takhfifkala = RemoteObject.createImmutable("");
public static RemoteObject _backpage = RemoteObject.createImmutable("");
public static RemoteObject _shomarefaktor = RemoteObject.createImmutable("");
public static RemoteObject _noefaktorclick = RemoteObject.createImmutable("");
public static RemoteObject _noefaktorchecked = RemoteObject.createImmutable("");
public static RemoteObject _servicegpsactive = RemoteObject.createImmutable(0);
public static RemoteObject _c_tafzili = RemoteObject.createImmutable("");
public static RemoteObject _n_tafzili = RemoteObject.createImmutable("");
public static RemoteObject _address_tafzili = RemoteObject.createImmutable("");
public static RemoteObject _tell_tafzili = RemoteObject.createImmutable("");
public static RemoteObject _version = RemoteObject.createImmutable("");
public static RemoteObject _namayeshkalasefr = RemoteObject.createImmutable("");
public static RemoteObject _newversion = RemoteObject.createImmutable("");
public static RemoteObject _linkdownload = RemoteObject.createImmutable("");
public static RemoteObject _c_layekala = RemoteObject.createImmutable("");
public static RemoteObject _c_layeashkhas = RemoteObject.createImmutable("");
public static RemoteObject _datefaktor = RemoteObject.createImmutable("");
public static RemoteObject _vaziatpardakhtfaktor = RemoteObject.createImmutable("");
public static RemoteObject _printbuffer = RemoteObject.createImmutable("");
public static RemoteObject _btadmin = RemoteObject.declareNull("anywheresoftware.b4a.objects.Serial.BluetoothAdmin");
public static RemoteObject _btconnection = RemoteObject.declareNull("anywheresoftware.b4a.objects.Serial");
public static RemoteObject _printers = RemoteObject.declareNull("anywheresoftware.b4a.objects.streams.File.TextWriterWrapper");
public static RemoteObject _typegetdata = RemoteObject.createImmutable("");
public static RemoteObject _loadenable = RemoteObject.createImmutable(false);
public static RemoteObject _pausestate = RemoteObject.createImmutable(false);
public static RemoteObject _deviceid = RemoteObject.createImmutable("");
public static RemoteObject _isactive = RemoteObject.createImmutable(false);
public static RemoteObject _savefactorinlocation = RemoteObject.createImmutable(false);
public static RemoteObject _masafat = RemoteObject.createImmutable(0L);
public static RemoteObject _tokenpush = RemoteObject.createImmutable("");
public static RemoteObject _pushbody = RemoteObject.createImmutable("");
public static RemoteObject _dastrasigroupkala = RemoteObject.createImmutable(0);
public static RemoteObject _dastrasigroupashkhas = RemoteObject.createImmutable(0);
public static RemoteObject _originallistfaktor = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _textsizepdf = RemoteObject.createImmutable(0);
public static RemoteObject _bmtsignature = RemoteObject.declareNull("anywheresoftware.b4a.objects.drawable.CanvasWrapper.BitmapWrapper");
public static RemoteObject _gpsisenable = RemoteObject.createImmutable(false);
public static RemoteObject _printertype = RemoteObject.createImmutable(0);
public static RemoteObject _vaziat = RemoteObject.createImmutable(0);
public static RemoteObject _codemoshtari = RemoteObject.createImmutable("");
public static RemoteObject _imageurl = RemoteObject.createImmutable("");
public static RemoteObject _backtoactivity = RemoteObject.createImmutable("");
public static RemoteObject _appname = RemoteObject.createImmutable("");
public static RemoteObject _menutitle2 = RemoteObject.createImmutable("");
public static RemoteObject _appver = RemoteObject.createImmutable("");
public static RemoteObject _plan = RemoteObject.createImmutable("");
public static RemoteObject _code = RemoteObject.createImmutable("");
public static RemoteObject _haveshift = RemoteObject.createImmutable(false);
public static RemoteObject _etelaresani = RemoteObject.createImmutable("");
public static RemoteObject _fldnewmoshtari = RemoteObject.createImmutable("");
public static RemoteObject _showbedehkaran = RemoteObject.createImmutable("");
public static RemoteObject _noeget = RemoteObject.createImmutable("");
public static RemoteObject _isfloat = RemoteObject.createImmutable(false);
public static RemoteObject _rs = RemoteObject.declareNull("anywheresoftware.b4a.agraham.richstring.RichStringBuilder.RichString");
public static RemoteObject _page = RemoteObject.createImmutable("");
public static RemoteObject _gps = RemoteObject.createImmutable("");
public static RemoteObject _sabtgpsshakhs = RemoteObject.createImmutable("");
public static RemoteObject _showgpsshakhs = RemoteObject.createImmutable("");
public static RemoteObject _action = RemoteObject.createImmutable("");
public static RemoteObject _faktorselect = RemoteObject.createImmutable("");
public static RemoteObject _forooshbishazmojoodi = RemoteObject.createImmutable("");
public static RemoteObject _signature = RemoteObject.createImmutable("");
public static RemoteObject _voroodtozihkala = RemoteObject.createImmutable("");
public static RemoteObject _darsadsood = RemoteObject.createImmutable("");
public static RemoteObject _darsadtakhfifvizhe = RemoteObject.createImmutable(0);
public static RemoteObject _kharidbiashaz = RemoteObject.createImmutable("");
public static RemoteObject _datetimesend = RemoteObject.createImmutable("");
public static RemoteObject _datetimerecive = RemoteObject.createImmutable("");
public static RemoteObject _shomaresabt = RemoteObject.createImmutable("");
public static RemoteObject _iconlink = RemoteObject.createImmutable("");
public static RemoteObject _finalfaktor = RemoteObject.declareNull("ir.parsikhesab.pakhsh.mcode._finalfaktor_");
public static RemoteObject _su = RemoteObject.declareNull("anywheresoftware.b4a.objects.StringUtils");
public static RemoteObject _listnotif = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _codevisitorselect = RemoteObject.createImmutable("");
public static RemoteObject _codemoshtariselect = RemoteObject.createImmutable("");
public static RemoteObject _countshowgpsmap = RemoteObject.createImmutable("");
public static RemoteObject _tag = RemoteObject.declareNull("Object");
public static RemoteObject _admin = RemoteObject.createImmutable("");
public static RemoteObject _tozie = RemoteObject.createImmutable("");
public static RemoteObject _visitor = RemoteObject.createImmutable("");
public static RemoteObject _sendmarjoie = RemoteObject.createImmutable("");
public static RemoteObject _checkadmin = RemoteObject.createImmutable("");
public static RemoteObject _hidemojodi = RemoteObject.createImmutable("");
public static RemoteObject _mablaghkol = RemoteObject.createImmutable("");
public static RemoteObject _tozihat_faktor = RemoteObject.createImmutable("");
public static RemoteObject _noetasviefaktor = RemoteObject.createImmutable("");
public static RemoteObject _dateversion = RemoteObject.createImmutable("");
public static RemoteObject _isonlinedatafactor = RemoteObject.createImmutable("");
public static RemoteObject _feetip = RemoteObject.createImmutable("");
public static RemoteObject _feecode = RemoteObject.createImmutable("");
public static RemoteObject _piconline = RemoteObject.createImmutable("");
public static RemoteObject _connectionstatus = RemoteObject.createImmutable("");
public static RemoteObject _arraytasvieforkala = null;
public static RemoteObject _typeversion = RemoteObject.createImmutable("");
public static RemoteObject _numberversion = RemoteObject.createImmutable("");
public static RemoteObject _darkmode = RemoteObject.createImmutable("");
public static RemoteObject _colorprimary = RemoteObject.createImmutable(0);
public static RemoteObject _colorprimarydark = RemoteObject.createImmutable(0);
public static RemoteObject _coloraccent = RemoteObject.createImmutable(0);
public static RemoteObject _vpn = RemoteObject.createImmutable(false);
public static RemoteObject _intervalgps = RemoteObject.createImmutable(0);
public static RemoteObject _lat = RemoteObject.createImmutable("");
public static RemoteObject _lon = RemoteObject.createImmutable("");
public static RemoteObject _gethavaleflag = RemoteObject.createImmutable(0);
public static RemoteObject _shomarehavale = RemoteObject.createImmutable("");
public static RemoteObject _shomaredaryaft = RemoteObject.createImmutable("");
public static RemoteObject _videoselected = RemoteObject.createImmutable("");
public static RemoteObject _lstchangefeekala = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _downloadingdata = RemoteObject.createImmutable(false);
public static RemoteObject _gpsdateta = RemoteObject.createImmutable("");
public static RemoteObject _gpstimeaz = RemoteObject.createImmutable("");
public static RemoteObject _gpstimeta = RemoteObject.createImmutable("");
public static RemoteObject _getdataonline = RemoteObject.createImmutable("");
public static RemoteObject _daryaft = RemoteObject.createImmutable("");
public static RemoteObject _amani = RemoteObject.createImmutable("");
public static RemoteObject _isamani = RemoteObject.createImmutable("");
public static RemoteObject _setvisit = RemoteObject.createImmutable("");
public static RemoteObject _mojavezsefaresh = RemoteObject.createImmutable("");
public static RemoteObject _deleteashkhasnew = RemoteObject.createImmutable(false);
public static RemoteObject _rotatepic = RemoteObject.createImmutable(false);
public static RemoteObject _updateshakhs = RemoteObject.createImmutable(false);
public static RemoteObject _feechange = RemoteObject.createImmutable("");
public static RemoteObject _eshantiontabaghati = RemoteObject.createImmutable("");
public static RemoteObject _eshantiongroup = RemoteObject.createImmutable("");
public static RemoteObject _eshantionremove = RemoteObject.createImmutable("");
public static RemoteObject _counteshantiongroup = RemoteObject.createImmutable("");
public static RemoteObject _mandeetebar = RemoteObject.createImmutable("");
public static RemoteObject _mandehesab = RemoteObject.createImmutable("");
public static RemoteObject _manedetebarenable = RemoteObject.createImmutable(false);
public static RemoteObject _th = RemoteObject.declareNull("anywheresoftware.b4a.agraham.threading.Threading");
public static RemoteObject _linkposparsian = RemoteObject.createImmutable("");
public static RemoteObject _packagenameposparsian = RemoteObject.createImmutable("");
public static RemoteObject _statuspickala = RemoteObject.createImmutable("");
public static RemoteObject _codekalaimage = RemoteObject.createImmutable("");
public static RemoteObject _companyname = RemoteObject.createImmutable("");
public static RemoteObject _companytell = RemoteObject.createImmutable("");
public static RemoteObject _companyaddress = RemoteObject.createImmutable("");
public static RemoteObject _mobileisimportent = RemoteObject.createImmutable("");
public static RemoteObject _arzeshafzode = RemoteObject.createImmutable("");
public static RemoteObject _arzeshafzodeenable = RemoteObject.createImmutable("");
public static RemoteObject _updatesefaresh = RemoteObject.createImmutable(false);
public static RemoteObject _fuslat = RemoteObject.createImmutable("");
public static RemoteObject _fuslon = RemoteObject.createImmutable("");
public static RemoteObject _fusgettime = RemoteObject.createImmutable("");
public static RemoteObject _widgetenable = RemoteObject.createImmutable(false);
public static RemoteObject _editfactor = RemoteObject.createImmutable(false);
public static RemoteObject _tourvisit = RemoteObject.createImmutable("");
public static RemoteObject _receiver2 = RemoteObject.declareNull("PNBroadcastReceiver.PNBrodcastReceiver");
public static RemoteObject _tourvisitsw = RemoteObject.createImmutable(false);
public static RemoteObject _getdatastatus = RemoteObject.createImmutable(false);
public static RemoteObject _locationf = RemoteObject.declareNull("igolub.fused.b4a.location.android.location.LocationFWrapper.LocationFStatic");
public static RemoteObject _locationresult = RemoteObject.declareNull("igolub.fused.b4a.location.LocationResultWrapper.LocationResultConstants");
public static RemoteObject _locationrequest = RemoteObject.declareNull("igolub.fused.b4a.location.LocationRequestWrapper.LocationRequestConstants");
public static RemoteObject _priority = RemoteObject.declareNull("igolub.fused.b4a.location.staticmodules.PriorityWrapper");
public static RemoteObject _granularity = RemoteObject.declareNull("igolub.fused.b4a.location.staticmodules.GranularityWrapper");
public static RemoteObject _fileprovider = RemoteObject.declareNull("igolub.permissionmanager.b4a.PermissionsManagerFileProvider");
public static RemoteObject _permissionsmanager = RemoteObject.declareNull("igolub.permissionmanager.b4a.PermissionsManagerConstants");
public static RemoteObject _dateutils = RemoteObject.declareNull("b4a.example.dateutils");
public static ir.parsikhesab.pakhsh.main _main = null;
public static ir.parsikhesab.pakhsh.act_main _act_main = null;
public static ir.parsikhesab.pakhsh.service_server _service_server = null;
public static ir.parsikhesab.pakhsh.mycode _mycode = null;
public static ir.parsikhesab.pakhsh.mdatabase _mdatabase = null;
public static ir.parsikhesab.pakhsh.gpswiget _gpswiget = null;
public static ir.parsikhesab.pakhsh.fusedlocationservice _fusedlocationservice = null;
public static ir.parsikhesab.pakhsh.service_helper _service_helper = null;
public static ir.parsikhesab.pakhsh.act_selectmantage _act_selectmantage = null;
public static ir.parsikhesab.pakhsh.act_reprizfactorvisitor _act_reprizfactorvisitor = null;
public static ir.parsikhesab.pakhsh.act_choose_report _act_choose_report = null;
public static ir.parsikhesab.pakhsh.act_emza _act_emza = null;
public static ir.parsikhesab.pakhsh.act_havaletozie _act_havaletozie = null;
public static ir.parsikhesab.pakhsh.act_imageslideshow _act_imageslideshow = null;
public static ir.parsikhesab.pakhsh.act_kala_listi _act_kala_listi = null;
public static ir.parsikhesab.pakhsh.act_kaladefault _act_kaladefault = null;
public static ir.parsikhesab.pakhsh.act_kalapaging _act_kalapaging = null;
public static ir.parsikhesab.pakhsh.act_kalapaging2 _act_kalapaging2 = null;
public static ir.parsikhesab.pakhsh.act_locationmoshtarian _act_locationmoshtarian = null;
public static ir.parsikhesab.pakhsh.act_locationvisitor _act_locationvisitor = null;
public static ir.parsikhesab.pakhsh.act_mali _act_mali = null;
public static ir.parsikhesab.pakhsh.act_moshtarian _act_moshtarian = null;
public static ir.parsikhesab.pakhsh.act_newashkhas _act_newashkhas = null;
public static ir.parsikhesab.pakhsh.act_notif _act_notif = null;
public static ir.parsikhesab.pakhsh.act_printmali _act_printmali = null;
public static ir.parsikhesab.pakhsh.act_printpic _act_printpic = null;
public static ir.parsikhesab.pakhsh.act_printpic2 _act_printpic2 = null;
public static ir.parsikhesab.pakhsh.act_profile _act_profile = null;
public static ir.parsikhesab.pakhsh.act_repfactors _act_repfactors = null;
public static ir.parsikhesab.pakhsh.act_repfactorvisitor _act_repfactorvisitor = null;
public static ir.parsikhesab.pakhsh.act_reportrizebargasht _act_reportrizebargasht = null;
public static ir.parsikhesab.pakhsh.act_reportsoorathesab _act_reportsoorathesab = null;
public static ir.parsikhesab.pakhsh.act_reportvisitor _act_reportvisitor = null;
public static ir.parsikhesab.pakhsh.act_reportvisitor2 _act_reportvisitor2 = null;
public static ir.parsikhesab.pakhsh.act_restore _act_restore = null;
public static ir.parsikhesab.pakhsh.act_rizefactorhavale _act_rizefactorhavale = null;
public static ir.parsikhesab.pakhsh.act_rizfaktor _act_rizfaktor = null;
public static ir.parsikhesab.pakhsh.act_rizhavale _act_rizhavale = null;
public static ir.parsikhesab.pakhsh.act_sabad _act_sabad = null;
public static ir.parsikhesab.pakhsh.act_sabtmarjooii _act_sabtmarjooii = null;
public static ir.parsikhesab.pakhsh.act_sabtrizcheck _act_sabtrizcheck = null;
public static ir.parsikhesab.pakhsh.act_saveinfocompany _act_saveinfocompany = null;
public static ir.parsikhesab.pakhsh.act_savelocation _act_savelocation = null;
public static ir.parsikhesab.pakhsh.act_search _act_search = null;
public static ir.parsikhesab.pakhsh.act_selfaktor _act_selfaktor = null;
public static ir.parsikhesab.pakhsh.act_senddata _act_senddata = null;
public static ir.parsikhesab.pakhsh.act_setting _act_setting = null;
public static ir.parsikhesab.pakhsh.act_settingpos _act_settingpos = null;
public static ir.parsikhesab.pakhsh.act_showlocation _act_showlocation = null;
public static ir.parsikhesab.pakhsh.act_support _act_support = null;
public static ir.parsikhesab.pakhsh.act_ticket _act_ticket = null;
public static ir.parsikhesab.pakhsh.act_video _act_video = null;
public static ir.parsikhesab.pakhsh.clskala _clskala = null;
public static ir.parsikhesab.pakhsh.dbutils _dbutils = null;
public static ir.parsikhesab.pakhsh.firebasemessaging _firebasemessaging = null;
public static ir.parsikhesab.pakhsh.geoservice _geoservice = null;
public static ir.parsikhesab.pakhsh.imagedownloader _imagedownloader = null;
public static ir.parsikhesab.pakhsh.myreceiver _myreceiver = null;
public static ir.parsikhesab.pakhsh.service_gps _service_gps = null;
public static ir.parsikhesab.pakhsh.service_notification _service_notification = null;
public static ir.parsikhesab.pakhsh.signaturecapture _signaturecapture = null;
public static ir.parsikhesab.pakhsh.starter _starter = null;
public static ir.parsikhesab.pakhsh.tracker _tracker = null;
public static ir.parsikhesab.pakhsh.wiget_service _wiget_service = null;
public static ir.parsikhesab.pakhsh.xmlviewex _xmlviewex = null;
public static ir.parsikhesab.pakhsh.newinst2 _newinst2 = null;
public static ir.parsikhesab.pakhsh.base64encodedecodeimage _base64encodedecodeimage = null;
public static ir.parsikhesab.pakhsh.httputils2service _httputils2service = null;
public static ir.parsikhesab.pakhsh.xuiviewsutils _xuiviewsutils = null;
  public Object[] GetGlobals() {
		return new Object[] {"Act_Choose_Report",Debug.moduleToString(ir.parsikhesab.pakhsh.act_choose_report.class),"Act_Emza",Debug.moduleToString(ir.parsikhesab.pakhsh.act_emza.class),"Act_HavaleTozie",Debug.moduleToString(ir.parsikhesab.pakhsh.act_havaletozie.class),"Act_ImageSlideShow",Debug.moduleToString(ir.parsikhesab.pakhsh.act_imageslideshow.class),"Act_Kala_listi",Debug.moduleToString(ir.parsikhesab.pakhsh.act_kala_listi.class),"Act_KalaDefault",Debug.moduleToString(ir.parsikhesab.pakhsh.act_kaladefault.class),"Act_KalaPaging",Debug.moduleToString(ir.parsikhesab.pakhsh.act_kalapaging.class),"Act_KalaPaging2",Debug.moduleToString(ir.parsikhesab.pakhsh.act_kalapaging2.class),"Act_LocationMoshtarian",Debug.moduleToString(ir.parsikhesab.pakhsh.act_locationmoshtarian.class),"Act_LocationVisitor",Debug.moduleToString(ir.parsikhesab.pakhsh.act_locationvisitor.class),"Act_Main",Debug.moduleToString(ir.parsikhesab.pakhsh.act_main.class),"Act_Mali",Debug.moduleToString(ir.parsikhesab.pakhsh.act_mali.class),"Act_Moshtarian",Debug.moduleToString(ir.parsikhesab.pakhsh.act_moshtarian.class),"Act_NewAshkhas",Debug.moduleToString(ir.parsikhesab.pakhsh.act_newashkhas.class),"Act_Notif",Debug.moduleToString(ir.parsikhesab.pakhsh.act_notif.class),"Act_PrintMali",Debug.moduleToString(ir.parsikhesab.pakhsh.act_printmali.class),"Act_PrintPic",Debug.moduleToString(ir.parsikhesab.pakhsh.act_printpic.class),"Act_PrintPic2",Debug.moduleToString(ir.parsikhesab.pakhsh.act_printpic2.class),"Act_Profile",Debug.moduleToString(ir.parsikhesab.pakhsh.act_profile.class),"Act_RepFactors",Debug.moduleToString(ir.parsikhesab.pakhsh.act_repfactors.class),"Act_RepFactorVisitor",Debug.moduleToString(ir.parsikhesab.pakhsh.act_repfactorvisitor.class),"Act_ReportRizeBargasht",Debug.moduleToString(ir.parsikhesab.pakhsh.act_reportrizebargasht.class),"Act_ReportSoorathesab",Debug.moduleToString(ir.parsikhesab.pakhsh.act_reportsoorathesab.class),"Act_ReportVisitor",Debug.moduleToString(ir.parsikhesab.pakhsh.act_reportvisitor.class),"Act_ReportVisitor2",Debug.moduleToString(ir.parsikhesab.pakhsh.act_reportvisitor2.class),"Act_RepRizFactorVisitor",Debug.moduleToString(ir.parsikhesab.pakhsh.act_reprizfactorvisitor.class),"Act_Restore",Debug.moduleToString(ir.parsikhesab.pakhsh.act_restore.class),"Act_RizeFactorHavale",Debug.moduleToString(ir.parsikhesab.pakhsh.act_rizefactorhavale.class),"Act_RizFaktor",Debug.moduleToString(ir.parsikhesab.pakhsh.act_rizfaktor.class),"Act_RizHavale",Debug.moduleToString(ir.parsikhesab.pakhsh.act_rizhavale.class),"Act_Sabad",Debug.moduleToString(ir.parsikhesab.pakhsh.act_sabad.class),"Act_SabtMarjooii",Debug.moduleToString(ir.parsikhesab.pakhsh.act_sabtmarjooii.class),"Act_SabtRizCheck",Debug.moduleToString(ir.parsikhesab.pakhsh.act_sabtrizcheck.class),"Act_SaveInfoCompany",Debug.moduleToString(ir.parsikhesab.pakhsh.act_saveinfocompany.class),"Act_SaveLocation",Debug.moduleToString(ir.parsikhesab.pakhsh.act_savelocation.class),"Act_Search",Debug.moduleToString(ir.parsikhesab.pakhsh.act_search.class),"Act_SelectMantage",Debug.moduleToString(ir.parsikhesab.pakhsh.act_selectmantage.class),"Act_SelFaktor",Debug.moduleToString(ir.parsikhesab.pakhsh.act_selfaktor.class),"Act_SendData",Debug.moduleToString(ir.parsikhesab.pakhsh.act_senddata.class),"Act_Setting",Debug.moduleToString(ir.parsikhesab.pakhsh.act_setting.class),"Act_SettingPos",Debug.moduleToString(ir.parsikhesab.pakhsh.act_settingpos.class),"Act_ShowLocation",Debug.moduleToString(ir.parsikhesab.pakhsh.act_showlocation.class),"Act_Support",Debug.moduleToString(ir.parsikhesab.pakhsh.act_support.class),"Act_Ticket",Debug.moduleToString(ir.parsikhesab.pakhsh.act_ticket.class),"Act_Video",Debug.moduleToString(ir.parsikhesab.pakhsh.act_video.class),"Action",mcode._action,"Address_Tafzili",mcode._address_tafzili,"Admin",mcode._admin,"Amani",mcode._amani,"AppName",mcode._appname,"AppVer",mcode._appver,"ArrayTasvieForKala",mcode._arraytasvieforkala,"ArzeshAfzode",mcode._arzeshafzode,"ArzeshAfzodeEnable",mcode._arzeshafzodeenable,"BackPage",mcode._backpage,"BackToActivity",mcode._backtoactivity,"Base64EncodeDecodeImage",Debug.moduleToString(ir.parsikhesab.pakhsh.base64encodedecodeimage.class),"bmtSignature",mcode._bmtsignature,"BtAdmin",mcode._btadmin,"BTConnection",mcode._btconnection,"C_LayeAshkhas",mcode._c_layeashkhas,"C_LayeKala",mcode._c_layekala,"C_Tafzili",mcode._c_tafzili,"C_Visitor",mcode._c_visitor,"CheckAdmin",mcode._checkadmin,"ClsKala",Debug.moduleToString(ir.parsikhesab.pakhsh.clskala.class),"Code",mcode._code,"CodeKalaImage",mcode._codekalaimage,"CodeMoshtari",mcode._codemoshtari,"CodeMoshtariSelect",mcode._codemoshtariselect,"CodeVisitorSelect",mcode._codevisitorselect,"colorAccent",mcode._coloraccent,"colorPrimary",mcode._colorprimary,"colorPrimaryDark",mcode._colorprimarydark,"CompanyAddress",mcode._companyaddress,"CompanyName",mcode._companyname,"CompanyTell",mcode._companytell,"ConnectionStatus",mcode._connectionstatus,"CountEshantionGroup",mcode._counteshantiongroup,"CountShowGpsMap",mcode._countshowgpsmap,"DarkMode",mcode._darkmode,"DarsadSood",mcode._darsadsood,"DarsadTakhfifVizhe",mcode._darsadtakhfifvizhe,"Daryaft",mcode._daryaft,"DastrasiGroupAshkhas",mcode._dastrasigroupashkhas,"DastrasiGroupKala",mcode._dastrasigroupkala,"DateFaktor",mcode._datefaktor,"DateTimeRecive",mcode._datetimerecive,"DateTimeSend",mcode._datetimesend,"DateUtils",mcode.mostCurrent._dateutils,"DateVersion",mcode._dateversion,"DBUtils",Debug.moduleToString(ir.parsikhesab.pakhsh.dbutils.class),"DeleteAshkhasNew",mcode._deleteashkhasnew,"DeviceId",mcode._deviceid,"downloadingData",mcode._downloadingdata,"editFactor",mcode._editfactor,"EshantionGroup",mcode._eshantiongroup,"EshantionRemove",mcode._eshantionremove,"EshantionTabaghati",mcode._eshantiontabaghati,"EtelaResani",mcode._etelaresani,"FaktorSelect",mcode._faktorselect,"FeeChange",mcode._feechange,"feeCode",mcode._feecode,"feeTip",mcode._feetip,"FileProvider",mcode.mostCurrent._fileprovider,"FinalFaktor",mcode._finalfaktor,"FirebaseMessaging",Debug.moduleToString(ir.parsikhesab.pakhsh.firebasemessaging.class),"fldNewMoshtari",mcode._fldnewmoshtari,"Font2",mcode._font2,"ForooshBishAzMojoodi",mcode._forooshbishazmojoodi,"FusedLocationService",Debug.moduleToString(ir.parsikhesab.pakhsh.fusedlocationservice.class),"fusGetTime",mcode._fusgettime,"fusLat",mcode._fuslat,"fusLon",mcode._fuslon,"GeoService",Debug.moduleToString(ir.parsikhesab.pakhsh.geoservice.class),"GetDataOnline",mcode._getdataonline,"GetDataStatus",mcode._getdatastatus,"GetHavaleFlag",mcode._gethavaleflag,"Gps",mcode._gps,"GpsDateTa",mcode._gpsdateta,"GpsIsEnable",mcode._gpsisenable,"GpsTimeAz",mcode._gpstimeaz,"GpsTimeTa",mcode._gpstimeta,"GpsWiget",Debug.moduleToString(ir.parsikhesab.pakhsh.gpswiget.class),"Granularity",mcode.mostCurrent._granularity,"HaveShift",mcode._haveshift,"HideMojodi",mcode._hidemojodi,"HttpUtils2Service",Debug.moduleToString(ir.parsikhesab.pakhsh.httputils2service.class),"IconLink",mcode._iconlink,"IconView",mcode._iconview,"ImageDownloader",Debug.moduleToString(ir.parsikhesab.pakhsh.imagedownloader.class),"ImageUrl",mcode._imageurl,"Imei",mcode._imei,"IntervalGps",mcode._intervalgps,"IsActive",mcode._isactive,"isAmani",mcode._isamani,"isFloat",mcode._isfloat,"IsOnlineDataFactor",mcode._isonlinedatafactor,"Json",mcode._json,"jsonG",mcode._jsong,"kalamanfi",mcode._kalamanfi,"KharidBiashAz",mcode._kharidbiashaz,"Lat",mcode._lat,"LinkDownload",mcode._linkdownload,"linkposparsian",mcode._linkposparsian,"ListNotif",mcode._listnotif,"LoadEnable",mcode._loadenable,"LocationF",mcode.mostCurrent._locationf,"LocationRequest",mcode.mostCurrent._locationrequest,"LocationResult",mcode.mostCurrent._locationresult,"Lon",mcode._lon,"lstChangeFeeKala",mcode._lstchangefeekala,"MablaghKol",mcode._mablaghkol,"Main",Debug.moduleToString(ir.parsikhesab.pakhsh.main.class),"MandeEtebar",mcode._mandeetebar,"MandeHesab",mcode._mandehesab,"ManedEtebarEnable",mcode._manedetebarenable,"Masafat",mcode._masafat,"MD",mcode._md,"MDatabase",Debug.moduleToString(ir.parsikhesab.pakhsh.mdatabase.class),"MenuTitle2",mcode._menutitle2,"MobileIsImportent",mcode._mobileisimportent,"MojavezSefaresh",mcode._mojavezsefaresh,"myCode",Debug.moduleToString(ir.parsikhesab.pakhsh.mycode.class),"MyReceiver",Debug.moduleToString(ir.parsikhesab.pakhsh.myreceiver.class),"N_Tafzili",mcode._n_tafzili,"N_Visitor",mcode._n_visitor,"NamayeshKalaSefr",mcode._namayeshkalasefr,"newinst2",Debug.moduleToString(ir.parsikhesab.pakhsh.newinst2.class),"NewVersion",mcode._newversion,"NoeFaktorChecked",mcode._noefaktorchecked,"NoeFaktorClick",mcode._noefaktorclick,"NoeGet",mcode._noeget,"NoeTasvieFaktor",mcode._noetasviefaktor,"NumberVersion",mcode._numberversion,"OriginalListFaktor",mcode._originallistfaktor,"P",mcode._p,"PackageNamePosParsian",mcode._packagenameposparsian,"page",mcode._page,"PauseState",mcode._pausestate,"PermissionsManager",mcode.mostCurrent._permissionsmanager,"PersianDate",mcode._persiandate,"PicOnline",mcode._piconline,"PImei",mcode._pimei,"placeHolder",mcode._placeholder,"Plan",mcode._plan,"PrintBuffer",mcode._printbuffer,"Printers",mcode._printers,"PrinterType",mcode._printertype,"Priority",mcode.mostCurrent._priority,"PushBody",mcode._pushbody,"RaghamAshar",mcode._raghamashar,"receiver2",mcode._receiver2,"RotatePic",mcode._rotatepic,"Rs",mcode._rs,"SabtGpsShakhs",mcode._sabtgpsshakhs,"SaveFactorInLocation",mcode._savefactorinlocation,"SendMarjoie",mcode._sendmarjoie,"Service_Gps",Debug.moduleToString(ir.parsikhesab.pakhsh.service_gps.class),"Service_Helper",Debug.moduleToString(ir.parsikhesab.pakhsh.service_helper.class),"Service_Notification",Debug.moduleToString(ir.parsikhesab.pakhsh.service_notification.class),"Service_Server",Debug.moduleToString(ir.parsikhesab.pakhsh.service_server.class),"ServiceGpsActive",mcode._servicegpsactive,"SetVisit",mcode._setvisit,"Sf",mcode._sf,"ShomareDaryaft",mcode._shomaredaryaft,"ShomareFaktor",mcode._shomarefaktor,"ShomareHavale",mcode._shomarehavale,"ShomareSabt",mcode._shomaresabt,"ShowBedehkaran",mcode._showbedehkaran,"ShowGpsShakhs",mcode._showgpsshakhs,"Signature",mcode._signature,"SignatureCapture",Debug.moduleToString(ir.parsikhesab.pakhsh.signaturecapture.class),"Sql1",mcode._sql1,"Starter",Debug.moduleToString(ir.parsikhesab.pakhsh.starter.class),"StatusPicKala",mcode._statuspickala,"strImei",mcode._strimei,"Su",mcode._su,"Tag",mcode._tag,"TaghirFeeKala",mcode._taghirfeekala,"TakhfifKala",mcode._takhfifkala,"Tell_Tafzili",mcode._tell_tafzili,"TextSizePdf",mcode._textsizepdf,"th",mcode._th,"TokenPush",mcode._tokenpush,"TourVisit",mcode._tourvisit,"TourVisitSW",mcode._tourvisitsw,"Tozie",mcode._tozie,"Tozihat_faktor",mcode._tozihat_faktor,"Tracker",Debug.moduleToString(ir.parsikhesab.pakhsh.tracker.class),"TypeGetData",mcode._typegetdata,"TypeVersion",mcode._typeversion,"UpdateSefaresh",mcode._updatesefaresh,"UpdateShakhs",mcode._updateshakhs,"Url",mcode._url,"VahedPool",mcode._vahedpool,"Vaziat",mcode._vaziat,"VaziatPardakhtFaktor",mcode._vaziatpardakhtfaktor,"Version",mcode._version,"VideoSelected",mcode._videoselected,"Visitor",mcode._visitor,"VoroodTozihKala",mcode._voroodtozihkala,"Vpn",mcode._vpn,"widgetEnable",mcode._widgetenable,"Wiget_Service",Debug.moduleToString(ir.parsikhesab.pakhsh.wiget_service.class),"XmlViewEx",Debug.moduleToString(ir.parsikhesab.pakhsh.xmlviewex.class),"XUIViewsUtils",Debug.moduleToString(ir.parsikhesab.pakhsh.xuiviewsutils.class)};
}
}